In [41]:
import pandas as pd
import numpy as np

In [42]:
df = pd.read_csv('data/precios_of.csv')
df

,nounderline_URL,nounderline,Like1
0,https://www.warhammer.com/en-US/shop/legio-cus...,Custodian Dreadnought,$77.00
1,https://www.warhammer.com/en-US/shop/legio-cus...,Sentinel Guard Sodality,$73.50
2,https://www.warhammer.com/en-US/shop/legio-cus...,Shield Captain,$43.50
3,https://www.warhammer.com/en-US/shop/legio-cus...,Venatari Sodality,$82.00
4,https://www.warhammer.com/en-US/shop/legio-cus...,Custodian Guard Sodality,$73.50
...,...,...,...
931,https://www.warhammer.com/en-US/shop/kill-team...,Kill Team: Canoptek Circle,$77.00
932,https://www.warhammer.com/en-US/shop/ultramari...,Victrix Honour Guard,$65.00
933,https://www.warhammer.com/en-US/shop/marneus-c...,Marneus Calgar in Armour of Antilochus,$55.50
934,https://www.warhammer.com/en-US/shop/imperial-...,Knight Preceptor/Canis Rex,$194.00
935,https://www.warhammer.com/en-US/shop/seraptek-...,Seraptek Heavy Construct with Synaptic Obliter...,$400.00

In [43]:
alfa = df.iloc[0:, 1:]
alfa

                                           nounderline    Like1
0                                Custodian Dreadnought   $77.00
1                              Sentinel Guard Sodality   $73.50
2                                       Shield Captain   $43.50
3                                    Venatari Sodality   $82.00
4                             Custodian Guard Sodality   $73.50
..                                                 ...      ...
931                         Kill Team: Canoptek Circle   $77.00
932                               Victrix Honour Guard   $65.00
933             Marneus Calgar in Armour of Antilochus   $55.50
934                         Knight Preceptor/Canis Rex  $194.00
935  Seraptek Heavy Construct with Synaptic Obliter...  $400.00

[936 rows x 2 columns]

In [44]:
faction = ['Craftworlds',
 'Drukhari',
 'Harlequins',
 'Ynnari',
 'Genestealer_Cult',
 'Tyranids',
 'Necrons',
 'Orks',
 'Tau_Empire',
 'Space_Marines',
 'Supplement_Marines',
 'Blood_Angels',
 'Dark_Angels',
 'Space_Wolves',
 'Deathwatch',
 'Grey_Knights',
 'Astra_Militarum',
 'Adepta_Sororitas',
 'Adeptus_Custodes',
 'Adeptus_Mechanicus',
 'Imperial_Assassins',
 'Imperial_Knights',
 'Inquisition',
 'Chaos_Daemons',
 'Chaos_Knights',
 'Chaos_Space_Marines',
 'Death_Guard',
 'Thousand_Sons']

In [45]:
beta = alfa.rename(columns={'Like1': 'price'})
beta

                                           nounderline    price
0                                Custodian Dreadnought   $77.00
1                              Sentinel Guard Sodality   $73.50
2                                       Shield Captain   $43.50
3                                    Venatari Sodality   $82.00
4                             Custodian Guard Sodality   $73.50
..                                                 ...      ...
931                         Kill Team: Canoptek Circle   $77.00
932                               Victrix Honour Guard   $65.00
933             Marneus Calgar in Armour of Antilochus   $55.50
934                         Knight Preceptor/Canis Rex  $194.00
935  Seraptek Heavy Construct with Synaptic Obliter...  $400.00

[936 rows x 2 columns]

In [46]:
beta['price'] = beta['price'].str.replace('$', '')
beta

                                           nounderline   price
0                                Custodian Dreadnought   77.00
1                              Sentinel Guard Sodality   73.50
2                                       Shield Captain   43.50
3                                    Venatari Sodality   82.00
4                             Custodian Guard Sodality   73.50
..                                                 ...     ...
931                         Kill Team: Canoptek Circle   77.00
932                               Victrix Honour Guard   65.00
933             Marneus Calgar in Armour of Antilochus   55.50
934                         Knight Preceptor/Canis Rex  194.00
935  Seraptek Heavy Construct with Synaptic Obliter...  400.00

[936 rows x 2 columns]

In [47]:
beta['price'] = pd.to_numeric(beta['price'], errors='coerce')
beta['price'] = (beta['price'] * 0.92).round(2)
beta

                                           nounderline   price
0                                Custodian Dreadnought   70.84
1                              Sentinel Guard Sodality   67.62
2                                       Shield Captain   40.02
3                                    Venatari Sodality   75.44
4                             Custodian Guard Sodality   67.62
..                                                 ...     ...
931                         Kill Team: Canoptek Circle   70.84
932                               Victrix Honour Guard   59.80
933             Marneus Calgar in Armour of Antilochus   51.06
934                         Knight Preceptor/Canis Rex  178.48
935  Seraptek Heavy Construct with Synaptic Obliter...  368.00

[936 rows x 2 columns]

In [48]:
beta['game'] = beta['nounderline'].str.split(':').str[0]
beta['mini'] = beta['nounderline'].str.split(':').str[1]

no_colon = beta['mini'].isna()
beta.loc[no_colon, 'mini'] = beta.loc[no_colon, 'game']
beta.loc[no_colon, 'game'] = None

gamma = beta.drop('nounderline', axis=1)
gamma

      price       game                                               mini
0     70.84       None                              Custodian Dreadnought
1     67.62       None                            Sentinel Guard Sodality
2     40.02       None                                     Shield Captain
3     75.44       None                                  Venatari Sodality
4     67.62       None                           Custodian Guard Sodality
..      ...        ...                                                ...
931   70.84  Kill Team                                    Canoptek Circle
932   59.80       None                               Victrix Honour Guard
933   51.06       None             Marneus Calgar in Armour of Antilochus
934  178.48       None                         Knight Preceptor/Canis Rex
935  368.00       None  Seraptek Heavy Construct with Synaptic Obliter...

[936 rows x 3 columns]

In [49]:
gamma['faction'] = gamma['game'].apply(
    lambda x: x if str(x).lower() in faction else None
)
gamma

,price,game,mini,faction
0,70.84,None,Custodian Dreadnought,None
1,67.62,None,Sentinel Guard Sodality,None
2,40.02,None,Shield Captain,None
3,75.44,None,Venatari Sodality,None
4,67.62,None,Custodian Guard Sodality,None
...,...,...,...,...
931,70.84,Kill Team,Canoptek Circle,None
932,59.80,None,Victrix Honour Guard,None
933,51.06,None,Marneus Calgar in Armour of Antilochus,None
934,178.48,None,Knight Preceptor/Canis Rex,None
935,368.00,None,Seraptek Heavy Construct with Synaptic Obliter...,None

In [50]:
gamma = gamma[~gamma['faction'].str.contains('Kill|Warhammer|Codex|cards|Easy|Wh40|40|Citadel|Tape|Liquid|Contrast|Air|Shade|Dry|Technical|Layer|Journal|Battlezone|B/Z|Battlefield|Sector|S/Imperialis|Hh', na=False)]
gamma = gamma[~gamma['game'].str.contains('Kill|Warhammer|Codex|cards|Easy|Wh40|40|Citadel|Tape|Liquid|Contrast|Air|Shade|Dry|Technical|Layer|Journal|Battlezone|B/Z|Battlefield|Sector|S/Imperialis|Hh|Terrain', na=False)]
gamma = gamma[~gamma['mini'].str.contains('Cards|Spa|Eng|Pb|Hb|Celebration|Citadel|Book|(6 Pack)|Dice|Ruins|Novel', na=False)]
gamma = gamma.reset_index(drop=True)

C:\Users\Varushet\AppData\Local\Temp\ipykernel_16140\430581735.py:3: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  gamma = gamma[~gamma['mini'].str.contains('Cards|Spa|Eng|Pb|Hb|Celebration|Citadel|Book|(6 Pack)|Dice|Ruins|Novel', na=False)]

In [51]:
def assign_faction(text):
    if pd.isna(text):
        return np.nan
    
    factions = ['Craftworlds',
        'Drukhari',
        'Harlequins',
        'Ynnari',
        'Genestealer_Cult',
        'Tyranids',
        'Necrons',
        'Orks',
        'Tau_Empire',
        'Chaos_Space_Marines',
        'Space_Marines',
        'Supplement_Marines',
        'Blood_Angels',
        'Dark_Angels',
        'Space_Wolves',
        'Deathwatch',
        'Grey_Knights',
        'Astra_Militarum',
        'Adepta_Sororitas',
        'Adeptus_Custodes',
        'Adeptus_Mechanicus',
        'Imperial_Assassins',
        'Imperial_Knights',
        'Inquisition',
        'Chaos_Daemons',
        'Chaos_Knights',
        'Death_Guard',
        'Thousand_Sons']
    
    for f in factions:
        faction_name = f.replace('_', ' ')
        if faction_name in text:
            clean = text.replace(faction_name, '').strip()
            clean = ' '.join(clean.split())
            return f, clean
    return np.nan, text

gamma[['faction', 'mini']] = gamma['mini'].apply(assign_faction).apply(pd.Series)
gamma

      price  game                                               mini faction
0     70.84  None                              Custodian Dreadnought     NaN
1     67.62  None                            Sentinel Guard Sodality     NaN
2     40.02  None                                     Shield Captain     NaN
3     75.44  None                                  Venatari Sodality     NaN
4     67.62  None                           Custodian Guard Sodality     NaN
..      ...   ...                                                ...     ...
843  119.60  None                    C'tan Shard of the Nightbringer     NaN
844   59.80  None                               Victrix Honour Guard     NaN
845   51.06  None             Marneus Calgar in Armour of Antilochus     NaN
846  178.48  None                         Knight Preceptor/Canis Rex     NaN
847  368.00  None  Seraptek Heavy Construct with Synaptic Obliter...     NaN

[848 rows x 4 columns]

In [52]:
gamma[~gamma['game'].isna()]

,price,game,mini,faction
13,156.40,Eye of Terror Battalion,,Adeptus_Mechanicus
14,193.20,Eye of Terror Battalion,,Imperial_Knights
23,156.40,Combat Patrol,,Drukhari
24,156.40,Combat Patrol,Leagues of Votann,NaN
25,156.40,Combat Patrol,Tyranid Assault Brood,NaN
26,156.40,Combat Patrol,Black Templars,NaN
27,156.40,Combat Patrol,,Grey_Knights
28,156.40,Combat Patrol,,Thousand_Sons
29,156.40,Combat Patrol,Emperor's Children,NaN
30,156.40,Combat Patrol,World Eaters,NaN
31,156.40,Combat Patrol,Aeldari,NaN
32,156.40,Combat Patrol,,Astra_Militarum
33,156.40,Combat Patrol,,Blood_Angels
34,156.40,Combat Patrol,Imperial Agents,NaN
35,156.40,Combat Patrol,s,Genestealer_Cult
36,156.40,Combat Patrol,,Adepta_Sororitas
37,156.40,Combat Patrol,T’au Empire,NaN
38,156.40,Combat Patrol,,Adeptus_Custodes
39,156.40,Combat Patrol,,Orks
40,156.40,Combat Patrol,,Dark_Angels
41,156.40,Combat Patrol,,Adeptus_Mechanicus
42,156.40,Combat Patrol,,Necrons
178,156.40,Space Marines,Honoured of the Chapter,NaN
308,55.20,Talons of the Emperor,Valerian and Aleya,NaN
329,55.20,Syll'Esske,The Vengeful Allegiance,NaN
518,55.20,Mek Gunz,Traktor Kannon,NaN
520,55.20,Mek Gunz,Kustom Mega-kannon,NaN
521,55.20,Mek Gunz,Smasha Gun,NaN
522,55.20,Mek Gunz,Bubblechukka,NaN
610,138.00,Spearhead,Blades of Khorne – Fangs of the Blood God,NaN
691,32.20,Black Templars,Upgrades and Transfers,NaN
717,35.88,Space Marines,Lieutenant,NaN
725,32.20,Tyranids,Termagants and Ripper Swarm + Paints Set,NaN
726,32.20,Space Marines,Infernus Marines + Paints Set,NaN
728,38.64,Boarding Actions,Void War Bases,NaN
730,NaN,Middle-earth™ Strategy Battle Game,The Best of White Dwarf Magazine (ePub),NaN
732,32.20,Chapter Approved 2025-26,Mission Deck,NaN
733,55.20,Crusade,Armageddon,NaN
734,32.20,Dark Angels,Upgrades and Transfers,NaN
737,248.40,Eye of Terror Battalion,Sons of Dorn,NaN
740,156.40,Combat Patrol,Aeldari Corsairs,NaN
742,69.00,Eye of Terror,Reign of Iron – War for the Cadian Gate,NaN
743,115.00,Eye of Terror,Reign of Iron – War for the Cadian Gate (Coll...,NaN
744,156.40,Combat Patrol,,Death_Guard

In [53]:
gamma[gamma['mini'] == 'Leagues of Votann']

Empty DataFrame
Columns: [price, game, mini, faction]
Index: []

In [54]:
faction_map = {
    'Craftworld': 'Craftworlds',
    'Aeldari': 'Craftworlds',
    'Drukhari': 'Drukhari',
    'Dark Eldar': 'Drukhari',
    'Harlequin': 'Harlequins',
    'Ynnari': 'Ynnari',
    'Genestealer': 'Genestealer_Cult',
    'GSC': 'Genestealer_Cult',
    'Tyranids': 'Tyranids',
    'Tyranid': 'Tyranids',
    'Necron': 'Necrons',
    'Ork': 'Orks',
    'Tau': 'Tau_Empire',
    "T'au": 'Tau_Empire',
    "T’au": 'Tau_Empire',
    'Space Marine': 'Space_Marines',
    'Space Marines': 'Space_Marines',
    'Primaris': 'Space_Marines',
    'Blood Angel': 'Blood_Angels',
    'Dark Angel': 'Dark_Angels',
    'Space Wolf': 'Space_Wolves',
    'Deathwatch': 'Deathwatch',
    'Grey Knight': 'Grey_Knights',
    'Astra Militarum': 'Astra_Militarum',
    'Sororitas': 'Adepta_Sororitas',
    'Sister': 'Adepta_Sororitas',
    'Adepta': 'Adepta_Sororitas',
    'Custodes': 'Adeptus_Custodes',
    'Adeptus Mechanicus': 'Adeptus_Mechanicus',
    'AdMech': 'Adeptus_Mechanicus',
    'Imperial Assassin': 'Imperial_Assassins',
    'Assassin': 'Imperial_Assassins',
    'Imperial Knight': 'Imperial_Knights',
    'Inquisitor': 'Inquisition',
    'Inquisition': 'Inquisition',
    'Chaos Daemon': 'Chaos_Daemons',
    'Daemon': 'Chaos_Daemons',
    'Chaos Knight': 'Chaos_Knights',
    'Chaos Space Marine': 'Chaos_Space_Marines',
    'CSM': 'Chaos_Space_Marines',
    'Death Guard': 'Death_Guard',
    'Thousand Son': 'Thousand_Sons',
    # Nuevos del segundo listado:
    'Astra Telepathica': 'Adeptus_Custodes',
    'Tallyman': 'Chaos_Daemons',
    'Templars': 'Supplement_Marines',
    'Angels': 'Supplement_Marines',
    'Black Legion': 'Chaos_Space_Marines',
    'Ultramarines': 'Supplement_Marines',
    'Iron Hand': 'Supplement_Marines',
    'Raven Guard': 'Supplement_Marines',
    'Salamanders': 'Supplement_Marines',
    'Imperial Fist': 'Supplement_Marines',
    'White Scar': 'Supplement_Marines',
    'S/Marine': 'Space_Marines',
    'Steel Legion': 'Astra_Militarum',
    'A/I': 'Astra_Militarum',
    'Eldar Dark': 'Drukhari',
    'Gunship': 'Tau_Empire',
    'Cult': 'Chaos_Daemons',
    'Genestealers': 'Genestealer_Cult',
    'Assassinorum': 'Imperial_Assassins',
    'A/Soror': 'Adepta_Sororitas',
}

name_map = {
    'Farseer': 'Craftworlds',
    'Howling Banshee': 'Craftworlds',
    'Custodian': 'Adeptus_Custodes',
    'Dire Avenger': 'Craftworlds',
    'Sodality': 'Adeptus_Custodes',
    'Warp Spider': 'Craftworlds',
    'Swooping Hawk': 'Craftworlds',
    'Striking Scorpion': 'Craftworlds',
    'Fire Dragon': 'Craftworlds',
    'Guardian': 'Craftworlds',
    'Warlock': 'Craftworlds',
    'Avatar': 'Craftworlds',
    'Vyper': 'Craftworlds',
    'Wave Serpent': 'Craftworlds',
    'Wraithguard': 'Craftworlds',
    'Wraithlord': 'Craftworlds',
    'Wraithknight': 'Craftworlds',
    'Ranger': 'Craftworlds',
    'Shining Spear': 'Craftworlds',
    'Kabalite': 'Drukhari',
    'Wych': 'Drukhari',
    'Incubi': 'Drukhari',
    'Haemonculus': 'Drukhari',
    'Archon': 'Drukhari',
    'Succubus': 'Drukhari',
    'Reaver': 'Drukhari',
    'Hellion': 'Drukhari',
    'Mandrake': 'Drukhari',
    'Ravager': 'Drukhari',
    'Raider': 'Drukhari',
    'Venom': 'Drukhari',
    'Cronos': 'Drukhari',
    'Talos': 'Drukhari',
    'Lelith': 'Drukhari',
    'Drazhar': 'Drukhari',
    'Grotesque': 'Drukhari',
    'Wrack': 'Drukhari',
    'Scourge': 'Drukhari',
    'Troupe': 'Harlequins',
    'Shadowseer': 'Harlequins',
    'Death Jester': 'Harlequins',
    'Solitaire': 'Harlequins',
    'Voidweaver': 'Harlequins',
    'Starweaver': 'Harlequins',
    'Yvraine': 'Ynnari',
    'The Visarch': 'Ynnari',
    'The Yncarne': 'Ynnari',
    'Cultist': 'Genestealer_Cult',
    'Acolyte': 'Genestealer_Cult',
    'Patriarch': 'Genestealer_Cult',
    'Magus': 'Genestealer_Cult',
    'Metamorph': 'Genestealer_Cult',
    'Neophyte': 'Genestealer_Cult',
    'Aberrant': 'Genestealer_Cult',
    'Kelermorph': 'Genestealer_Cult',
    'Hive Guard': 'Tyranids',
    'Hormagaunt': 'Tyranids',
    'Termagant': 'Tyranids',
    'Gaunt': 'Tyranids',
    'Warrior': 'Tyranids',
    'Carnifex': 'Tyranids',
    'Trygon': 'Tyranids',
    'Ravener': 'Tyranids',
    'Lictor': 'Tyranids',
    'Haruspex': 'Tyranids',
    'Zoanthrope': 'Tyranids',
    'Neurotyrant': 'Tyranids',
    'Biovores': 'Tyranids',
    'Myphitic': 'Tyranids',
    'Tervigon': 'Tyranids',
    'Old One Eye': 'Tyranids',
    'The Swarmlord': 'Tyranids',
    'Hive Tyrant': 'Tyranids',
    'Neurothrope': 'Tyranids',
    'Immortal': 'Necrons',
    'Lychguard': 'Necrons',
    'Deathmark': 'Necrons',
    'Flayed One': 'Necrons',
    'Canoptek': 'Necrons',
    'Monolith': 'Necrons',
    'Ghost Ark': 'Necrons',
    'Night Scythe': 'Necrons',
    'Doom Scythe': 'Necrons',
    'Tomb Blade': 'Necrons',
    'Spyder': 'Necrons',
    'Overlord': 'Necrons',
    'Cryptek': 'Necrons',
    'Lord': 'Necrons',
    'Triarch': 'Necrons',
    'Wraith': 'Necrons',
    'Destroyer': 'Necrons',
    'Cairn': 'Necrons',
    'Boyz': 'Orks',
    'Nob': 'Orks',
    'Warboss': 'Orks',
    'Mek': 'Orks',
    'Weirdboy': 'Orks',
    'Dok': 'Orks',
    'Flash Gitz': 'Orks',
    'Burna': 'Orks',
    'Shoota': 'Orks',
    'Slugga': 'Orks',
    'Trukk': 'Orks',
    'Deff Dread': 'Orks',
    'Killa Kan': 'Orks',
    'Looted Wagon': 'Orks',
    'Big Mek': 'Orks',
    'Ghazghkull': 'Orks',
    'Gretchin': 'Orks',
    'Snotling': 'Orks',
    'Fire Warrior': 'Tau_Empire',
    'Crisis': 'Tau_Empire',
    'Broadside': 'Tau_Empire',
    'Riptide': 'Tau_Empire',
    'Pathfinder': 'Tau_Empire',
    'Stealth': 'Tau_Empire',
    'Piranha': 'Tau_Empire',
    'Hammerhead': 'Tau_Empire',
    'Skyray': 'Tau_Empire',
    'XV': 'Tau_Empire',
    'Commander': 'Tau_Empire',
    'Ethereal': 'Tau_Empire',
    'Devilfish': 'Tau_Empire',
    'Intercessor': 'Space_Marines',
    'Tactical': 'Space_Marines',
    'Devastator': 'Space_Marines',
    'Assault': 'Space_Marines',
    'Sternguard': 'Space_Marines',
    'Vanguard': 'Space_Marines',
    'Scout': 'Space_Marines',
    'Aggressor': 'Space_Marines',
    'Eliminator': 'Space_Marines',
    'Inceptor': 'Space_Marines',
    'Suppressor': 'Space_Marines',
    'Reiver': 'Space_Marines',
    'Hellblaster': 'Space_Marines',
    'Outrider': 'Space_Marines',
    'Whirlwind': 'Space_Marines',
    'Rhino': 'Space_Marines',
    'Predator': 'Space_Marines',
    'Land Raider': 'Space_Marines',
    'Republik': 'Space_Marines',
    'Impulsor': 'Space_Marines',
    'Gladiator': 'Space_Marines',
    'Sanguinius': 'Blood_Angels',
    'Dante': 'Blood_Angels',
    'Death Company': 'Blood_Angels',
    'Furioso': 'Blood_Angels',
    'Baal': 'Blood_Angels',
    'Lemartes': 'Blood_Angels',
    'Inner Circle': 'Dark_Angels',
    'Belial': 'Dark_Angels',
    'Ravenwing': 'Dark_Angels',
    'Deathwing': 'Dark_Angels',
    'Wolf': 'Space_Wolves',
    'Thunderwolf': 'Space_Wolves',
    'Rune Priest': 'Space_Wolves',
    'Iron Priest': 'Space_Wolves',
    'Wolf Lord': 'Space_Wolves',
    'Wulfen': 'Space_Wolves',
    'Blood Claw': 'Space_Wolves',
    'Stormwolf': 'Space_Wolves',
    'Kill Team': 'Deathwatch',
    'Watch Master': 'Deathwatch',
    'Veteran': 'Deathwatch',
    'Brother': 'Grey_Knights',
    'Justicar': 'Grey_Knights',
    'Castellan': 'Grey_Knights',
    'Venerable': 'Grey_Knights',
    'Nemesis': 'Grey_Knights',
    'Purifier': 'Grey_Knights',
    'Cadian': 'Astra_Militarum',
    'Krieg': 'Astra_Militarum',
    'Kasrkin': 'Astra_Militarum',
    'Conscript': 'Astra_Militarum',
    'Chimera': 'Astra_Militarum',
    'Leman Russ': 'Astra_Militarum',
    'Basilisk': 'Astra_Militarum',
    'Baneblade': 'Astra_Militarum',
    'Trooper': 'Astra_Militarum',
    'Ogryn': 'Astra_Militarum',
    'Ratling': 'Astra_Militarum',
    'Commissar': 'Astra_Militarum',
    'Lord Solar': 'Astra_Militarum',
    'Tempestus': 'Astra_Militarum',
    'Canoness': 'Adepta_Sororitas',
    'Palatine': 'Adepta_Sororitas',
    'Seraphim': 'Adepta_Sororitas',
    'Celestian': 'Adepta_Sororitas',
    'Dominion': 'Adepta_Sororitas',
    'Battle Sister': 'Adepta_Sororitas',
    'Novitiate': 'Adepta_Sororitas',
    'Hospitaller': 'Adepta_Sororitas',
    'Preacher': 'Adepta_Sororitas',
    'Imagifier': 'Adepta_Sororitas',
    'Celestine': 'Adepta_Sororitas',
    'Paragon': 'Adepta_Sororitas',
    'Exorcist': 'Adepta_Sororitas',
    'Retributor': 'Adepta_Sororitas',
    'Shield Captain': 'Adeptus_Custodes',
    'Vertus Praetor': 'Adeptus_Custodes',
    'Sagittarum': 'Adeptus_Custodes',
    'Vexilus': 'Adeptus_Custodes',
    'Valiant': 'Adeptus_Custodes',
    'Telemon': 'Adeptus_Custodes',
    'Caladius': 'Adeptus_Custodes',
    'Coronus': 'Adeptus_Custodes',
    'Contemptor': 'Adeptus_Custodes',
    'Allarus': 'Adeptus_Custodes',
    'Trajann': 'Adeptus_Custodes',
    'Solaria': 'Adeptus_Custodes',
    'Skorpius': 'Adeptus_Mechanicus',
    'Kastelan': 'Adeptus_Mechanicus',
    'Sydonian': 'Adeptus_Mechanicus',
    'Ironstrider': 'Adeptus_Mechanicus',
    'Techpriest': 'Adeptus_Mechanicus',
    'Enginseer': 'Adeptus_Mechanicus',
    'Secutarii': 'Adeptus_Mechanicus',
    'Peltast': 'Adeptus_Mechanicus',
    'Hoplite': 'Adeptus_Mechanicus',
    'Hastarii': 'Adeptus_Mechanicus',
    'Maniple': 'Adeptus_Mechanicus',
    'Kataphron': 'Adeptus_Mechanicus',
    'Onslaught': 'Adeptus_Mechanicus',
    'Cawl': 'Adeptus_Mechanicus',
    'Vindicare': 'Imperial_Assassins',
    'Eversor': 'Imperial_Assassins',
    'Callidus': 'Imperial_Assassins',
    'Culexus': 'Imperial_Assassins',
    'Paladin': 'Imperial_Knights',
    'Errant': 'Imperial_Knights',
    'Crusader': 'Imperial_Knights',
    'Warden': 'Imperial_Knights',
    'Gallant': 'Imperial_Knights',
    'Armiger': 'Imperial_Knights',
    'Moira': 'Imperial_Knights',
    'Questoris': 'Imperial_Knights',
    'Warmaster': 'Imperial_Knights',
    'Bloodthirster': 'Chaos_Daemons',
    'Lord of Change': 'Chaos_Daemons',
    'Great Unclean One': 'Chaos_Daemons',
    'Keeper of Secrets': 'Chaos_Daemons',
    'Bloodletter': 'Chaos_Daemons',
    'Horror': 'Chaos_Daemons',
    'Plaguebearer': 'Chaos_Daemons',
    'Daemonette': 'Chaos_Daemons',
    'Screamer': 'Chaos_Daemons',
    'Exalted': 'Chaos_Daemons',
    'Desecrator': 'Chaos_Knights',
    'Decimator': 'Chaos_Knights',
    'Shroud': 'Chaos_Knights',
    'Stalker': 'Chaos_Knights',
    'Warg': 'Chaos_Knights',
    'Abominant': 'Chaos_Knights',
    'Mourneblade': 'Chaos_Knights',
    'Legion': 'Chaos_Space_Marines',
    'Champion': 'Chaos_Space_Marines',
    'Obliterator': 'Chaos_Space_Marines',
    'Possessed': 'Chaos_Space_Marines',
    'Havoc': 'Chaos_Space_Marines',
    'Raptor': 'Chaos_Space_Marines',
    'Sorcerer': 'Chaos_Space_Marines',
    'Terminator': 'Chaos_Space_Marines',
    'Mutilators': 'Chaos_Space_Marines',
    'Plague': 'Death_Guard',
    'Nurgle': 'Death_Guard',
    'Mortarion': 'Death_Guard',
    'Poxwalker': 'Death_Guard',
    'Poxbrute': 'Death_Guard',
    'Foetid Bloat': 'Death_Guard',
    'Blasphemy': 'Death_Guard',
    'Spawn': 'Death_Guard',
    'Tzeentch': 'Thousand_Sons',
    'Magnus': 'Thousand_Sons',
    'Rubric': 'Thousand_Sons',
    'Chaos Lord': 'Thousand_Sons',
    'Mutalith': 'Thousand_Sons',
    'Thulia': 'Adeptus_Mechanicus',
    'Daemon': 'Chaos_Daemons',
    'Khorne': 'Chaos_Daemons',
    'Kharn': 'Chaos_Daemons',
    'Skarbrand': 'Chaos_Daemons',
    'Syll': 'Chaos_Daemons',
    'Feculent': 'Chaos_Daemons',
    'Karanak': 'Chaos_Daemons',
    'Eisenhorn': 'Inquisition',
    'Ravenor': 'Inquisition',
    'Lord Inquisitor': 'Inquisition',
    'Lord Commissar': 'Inquisition',
    'Ciaphas Cain': 'Inquisition',
    'Marneus': 'Supplement_Marines',
    'Militarum': 'Astra_Militarum',
    'Aeronautica': 'Astra_Militarum',
    'Aer': 'Astra_Militarum',
    'Captain General': 'Adeptus_Custodes',
    'Daemons': 'Chaos_Daemons',
    'Chaos': 'Chaos_Daemons',
    'Saint': 'Adepta_Sororitas',
    'Knight': 'Imperial_Knights',
    'Titan': 'Imperial_Knights',
    'Mech': 'Adeptus_Mechanicus',
    'Talons': 'Adeptus_Custodes',
    'Tufts': 'Space_Marines',
    'Space Hulk': 'Space_Marines',
    'reavers': 'Chaos_Space_Marines',
    "C'tan" : 'Necrons',
    'Victrix': 'Supplement_Marines',
    "Emperor's Children": 'Chaos_Space_Marines',
    "World Eaters": 'Chaos_Space_Marines',
    "Imperial Agents": 'Deathwatch',
    'Seraptek': 'Necrons',
    'Leagues of Votann': 'Leagues of Votann',
    'Dorn': 'Supplement_Marines'
}

In [55]:
import re

def map_faction(text):
    if pd.isna(text):
        return np.nan, text
    
    # faction_map → SÍ elimina la coincidencia de 'all'
    for key, value in faction_map.items():
        pattern = r'\b' + re.escape(key) + r'\b'
        if re.search(pattern, text, re.IGNORECASE):
            clean = re.sub(pattern, '', text, flags=re.IGNORECASE).strip()
            clean = re.sub(r'\s+', ' ', clean).strip()
            return value, clean
    
    # name_map → NO elimina, conserva el texto original
    for key, value in name_map.items():
        pattern = r'\b' + re.escape(key) + r'\b'
        if re.search(pattern, text, re.IGNORECASE):
            return value, text
    
    return np.nan, text

# Aplicar fila por fila solo donde faction es NaN
for idx in gamma[gamma['faction'].isna()].index:
    faction, _ = map_faction(gamma.loc[idx, 'mini'])
    if pd.isna(faction):
        faction, _ = map_faction(gamma.loc[idx, 'game'])
    gamma.loc[idx, 'faction'] = faction

In [56]:
mask = ~gamma['game'].isna()
gamma['mini'] = gamma['mini'].replace(r'^\s*$', np.nan, regex=True)

In [57]:
# gamma.loc[mask, 'mini'] = gamma.loc[mask, 'mini'].fillna(gamma.loc[mask, 'game'])
gamma[~gamma['game'].isna()]

,price,game,mini,faction
13,156.40,Eye of Terror Battalion,NaN,Adeptus_Mechanicus
14,193.20,Eye of Terror Battalion,NaN,Imperial_Knights
23,156.40,Combat Patrol,NaN,Drukhari
24,156.40,Combat Patrol,Leagues of Votann,Leagues of Votann
25,156.40,Combat Patrol,Tyranid Assault Brood,Tyranids
26,156.40,Combat Patrol,Black Templars,Supplement_Marines
27,156.40,Combat Patrol,NaN,Grey_Knights
28,156.40,Combat Patrol,NaN,Thousand_Sons
29,156.40,Combat Patrol,Emperor's Children,Chaos_Space_Marines
30,156.40,Combat Patrol,World Eaters,Chaos_Space_Marines
31,156.40,Combat Patrol,Aeldari,Craftworlds
32,156.40,Combat Patrol,NaN,Astra_Militarum
33,156.40,Combat Patrol,NaN,Blood_Angels
34,156.40,Combat Patrol,Imperial Agents,Deathwatch
35,156.40,Combat Patrol,s,Genestealer_Cult
36,156.40,Combat Patrol,NaN,Adepta_Sororitas
37,156.40,Combat Patrol,T’au Empire,Tau_Empire
38,156.40,Combat Patrol,NaN,Adeptus_Custodes
39,156.40,Combat Patrol,NaN,Orks
40,156.40,Combat Patrol,NaN,Dark_Angels
41,156.40,Combat Patrol,NaN,Adeptus_Mechanicus
42,156.40,Combat Patrol,NaN,Necrons
178,156.40,Space Marines,Honoured of the Chapter,Space_Marines
308,55.20,Talons of the Emperor,Valerian and Aleya,Adeptus_Custodes
329,55.20,Syll'Esske,The Vengeful Allegiance,Chaos_Daemons
518,55.20,Mek Gunz,Traktor Kannon,Orks
520,55.20,Mek Gunz,Kustom Mega-kannon,Orks
521,55.20,Mek Gunz,Smasha Gun,Orks
522,55.20,Mek Gunz,Bubblechukka,Orks
610,138.00,Spearhead,Blades of Khorne – Fangs of the Blood God,Chaos_Daemons
691,32.20,Black Templars,Upgrades and Transfers,Supplement_Marines
717,35.88,Space Marines,Lieutenant,Space_Marines
725,32.20,Tyranids,Termagants and Ripper Swarm + Paints Set,Tyranids
726,32.20,Space Marines,Infernus Marines + Paints Set,Space_Marines
728,38.64,Boarding Actions,Void War Bases,NaN
730,NaN,Middle-earth™ Strategy Battle Game,The Best of White Dwarf Magazine (ePub),NaN
732,32.20,Chapter Approved 2025-26,Mission Deck,NaN
733,55.20,Crusade,Armageddon,NaN
734,32.20,Dark Angels,Upgrades and Transfers,Supplement_Marines
737,248.40,Eye of Terror Battalion,Sons of Dorn,Supplement_Marines
740,156.40,Combat Patrol,Aeldari Corsairs,Craftworlds
742,69.00,Eye of Terror,Reign of Iron – War for the Cadian Gate,Astra_Militarum
743,115.00,Eye of Terror,Reign of Iron – War for the Cadian Gate (Coll...,Astra_Militarum
744,156.40,Combat Patrol,NaN,Death_Guard

In [58]:
gamma = gamma.drop([728, 730, 732, 733, 738, 739, 742, 743]).reset_index(drop=True)
gamma[~gamma['game'].isna()]

,price,game,mini,faction
13,156.40,Eye of Terror Battalion,NaN,Adeptus_Mechanicus
14,193.20,Eye of Terror Battalion,NaN,Imperial_Knights
23,156.40,Combat Patrol,NaN,Drukhari
24,156.40,Combat Patrol,Leagues of Votann,Leagues of Votann
25,156.40,Combat Patrol,Tyranid Assault Brood,Tyranids
26,156.40,Combat Patrol,Black Templars,Supplement_Marines
27,156.40,Combat Patrol,NaN,Grey_Knights
28,156.40,Combat Patrol,NaN,Thousand_Sons
29,156.40,Combat Patrol,Emperor's Children,Chaos_Space_Marines
30,156.40,Combat Patrol,World Eaters,Chaos_Space_Marines
31,156.40,Combat Patrol,Aeldari,Craftworlds
32,156.40,Combat Patrol,NaN,Astra_Militarum
33,156.40,Combat Patrol,NaN,Blood_Angels
34,156.40,Combat Patrol,Imperial Agents,Deathwatch
35,156.40,Combat Patrol,s,Genestealer_Cult
36,156.40,Combat Patrol,NaN,Adepta_Sororitas
37,156.40,Combat Patrol,T’au Empire,Tau_Empire
38,156.40,Combat Patrol,NaN,Adeptus_Custodes
39,156.40,Combat Patrol,NaN,Orks
40,156.40,Combat Patrol,NaN,Dark_Angels
41,156.40,Combat Patrol,NaN,Adeptus_Mechanicus
42,156.40,Combat Patrol,NaN,Necrons
178,156.40,Space Marines,Honoured of the Chapter,Space_Marines
308,55.20,Talons of the Emperor,Valerian and Aleya,Adeptus_Custodes
329,55.20,Syll'Esske,The Vengeful Allegiance,Chaos_Daemons
518,55.20,Mek Gunz,Traktor Kannon,Orks
520,55.20,Mek Gunz,Kustom Mega-kannon,Orks
521,55.20,Mek Gunz,Smasha Gun,Orks
522,55.20,Mek Gunz,Bubblechukka,Orks
610,138.00,Spearhead,Blades of Khorne – Fangs of the Blood God,Chaos_Daemons
691,32.20,Black Templars,Upgrades and Transfers,Supplement_Marines
717,35.88,Space Marines,Lieutenant,Space_Marines
725,32.20,Tyranids,Termagants and Ripper Swarm + Paints Set,Tyranids
726,32.20,Space Marines,Infernus Marines + Paints Set,Space_Marines
730,32.20,Dark Angels,Upgrades and Transfers,Supplement_Marines
733,248.40,Eye of Terror Battalion,Sons of Dorn,Supplement_Marines
734,156.40,Combat Patrol,Aeldari Corsairs,Craftworlds
736,156.40,Combat Patrol,NaN,Death_Guard

In [59]:
# Cuando mini está vacío/NaN, usar game
gamma['mini'] = gamma['mini'].fillna(gamma['game'])

# Cuando game tiene valor y mini también, combinar ambos (si son diferentes)
mask_both = gamma['game'].notna() & gamma['mini'].notna() & (gamma['game'] != gamma['mini'])
gamma.loc[mask_both, 'mini'] = gamma.loc[mask_both, 'game'] + ' ' + gamma.loc[mask_both, 'mini']

# Cuando solo game tiene valor y mini no
mask_only_game = gamma['game'].notna() & gamma['mini'].isna()
gamma.loc[mask_only_game, 'mini'] = gamma.loc[mask_only_game, 'game']

# Eliminar columna game
gamma = gamma.drop('game', axis=1)

# Limpiar cualquier NaN restante
gamma['mini'] = gamma['mini'].fillna('')

# Verificar
print(f"NaN values: {gamma['mini'].isna().sum()}")
gamma

NaN values: 0

,price,mini,faction
0,70.84,Custodian Dreadnought,Adeptus_Custodes
1,67.62,Sentinel Guard Sodality,Adeptus_Custodes
2,40.02,Shield Captain,Adeptus_Custodes
3,75.44,Venatari Sodality,Adeptus_Custodes
4,67.62,Custodian Guard Sodality,Adeptus_Custodes
...,...,...,...
835,119.60,C'tan Shard of the Nightbringer,Necrons
836,59.80,Victrix Honour Guard,Supplement_Marines
837,51.06,Marneus Calgar in Armour of Antilochus,Supplement_Marines
838,178.48,Knight Preceptor/Canis Rex,Imperial_Knights
839,368.00,Seraptek Heavy Construct with Synaptic Obliter...,Necrons

In [ ]:
gamma.to_csv('../data/clear_data/df_prices_v1.csv', index=False)
gamma.head(50)

     price                                  mini              faction
0    70.84                 Custodian Dreadnought     Adeptus_Custodes
1    67.62               Sentinel Guard Sodality     Adeptus_Custodes
2    40.02                        Shield Captain     Adeptus_Custodes
3    75.44                     Venatari Sodality     Adeptus_Custodes
4    67.62              Custodian Guard Sodality     Adeptus_Custodes
5    92.00        Caladius Annihilator Grav-tank     Adeptus_Custodes
6    92.00                    Caladius Grav-tank     Adeptus_Custodes
7   116.84                  Coronus Grav-carrier     Adeptus_Custodes
8    55.20                              Hastarii   Adeptus_Mechanicus
9    59.80                          Thulia Ghuld   Adeptus_Mechanicus
10   63.48                            Mutilators  Chaos_Space_Marines
11   32.20                Iron Warriors Upgrades                  NaN
12  156.40                       Knight Destrier     Imperial_Knights
13  156.40               Eye of Terror Battalion   Adeptus_Mechanicus
14  193.20               Eye of Terror Battalion     Imperial_Knights
15   40.02          Tyranid Prime with Lash Whip             Tyranids
16   59.80                        Vyper/Starfang          Craftworlds
17   59.80                   Corsair Voidreavers                  NaN
18   55.20                    Corsair Skyreavers                  NaN
19   40.02                              Kharseth                  NaN
20   43.24                          Prince Yriel                  NaN
21   32.20   Red Corsairs Upgrades and Transfers                  NaN
22   59.80                  Red Corsairs Raiders                  NaN
23  156.40                         Combat Patrol             Drukhari
24  156.40      Combat Patrol  Leagues of Votann    Leagues of Votann
25  156.40  Combat Patrol  Tyranid Assault Brood             Tyranids
26  156.40         Combat Patrol  Black Templars   Supplement_Marines
27  156.40                         Combat Patrol         Grey_Knights
28  156.40                         Combat Patrol        Thousand_Sons
29  156.40     Combat Patrol  Emperor's Children  Chaos_Space_Marines
30  156.40           Combat Patrol  World Eaters  Chaos_Space_Marines
31  156.40                Combat Patrol  Aeldari          Craftworlds
32  156.40                         Combat Patrol      Astra_Militarum
33  156.40                         Combat Patrol         Blood_Angels
34  156.40        Combat Patrol  Imperial Agents           Deathwatch
35  156.40                       Combat Patrol s     Genestealer_Cult
36  156.40                         Combat Patrol     Adepta_Sororitas
37  156.40            Combat Patrol  T’au Empire           Tau_Empire
38  156.40                         Combat Patrol     Adeptus_Custodes
39  156.40                         Combat Patrol                 Orks
40  156.40                         Combat Patrol          Dark_Angels
41  156.40                         Combat Patrol   Adeptus_Mechanicus
42  156.40                         Combat Patrol              Necrons
43   44.16                                Wyches                  NaN
44   63.48                             Manticore                  NaN
45   29.44                        Support Weapon                  NaN
46   73.60                         Baal Predator        Space_Marines
47   63.48                              Basilisk      Astra_Militarum
48   59.80                               Chimera      Astra_Militarum
49   59.80                            Killa Kans                  NaN