In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('data/prices.csv')
df

      ss_code                             product_name  price currency
0       01-07         ADEPTUS CUSTODES CUSTODIAN GUARD   61.0      USD
1       01-08     ASTRA TELEPATHICA SISTERS OF SILENCE   50.0      USD
2       01-10          CAPTAIN-GENERAL TRAJANN VALORIS   39.0      USD
3       01-11       ADEPTUS CUSTODES CUSTODIAN WARDENS   61.0      USD
4       01-12         ADEPTUS CUSTODES VERTUS PRAETORS   61.0      USD
...       ...                                      ...    ...      ...
1615   SMH-05  SPACE MARINE HEROES 3 F/DISPENSER (ROW)   13.0      USD
1616  WD01-60       WHITE DWARF 460 (JAN-21) (ENGLISH)   10.0      USD
1617  WD02-60       WHITE DWARF 461 (FEB-21) (ENGLISH)   10.0      USD
1618  WD11-60       WHITE DWARF 458 (NOV-20) (ENGLISH)   10.0      USD
1619  WD12-60       WHITE DWARF 459 (DEC-20) (ENGLISH)   10.0      USD

[1620 rows x 4 columns]

In [3]:
df = df.drop(columns=['ss_code', 'currency'])
df

                                 product_name  price
0            ADEPTUS CUSTODES CUSTODIAN GUARD   61.0
1        ASTRA TELEPATHICA SISTERS OF SILENCE   50.0
2             CAPTAIN-GENERAL TRAJANN VALORIS   39.0
3          ADEPTUS CUSTODES CUSTODIAN WARDENS   61.0
4            ADEPTUS CUSTODES VERTUS PRAETORS   61.0
...                                       ...    ...
1615  SPACE MARINE HEROES 3 F/DISPENSER (ROW)   13.0
1616       WHITE DWARF 460 (JAN-21) (ENGLISH)   10.0
1617       WHITE DWARF 461 (FEB-21) (ENGLISH)   10.0
1618       WHITE DWARF 458 (NOV-20) (ENGLISH)   10.0
1619       WHITE DWARF 459 (DEC-20) (ENGLISH)   10.0

[1620 rows x 2 columns]

In [4]:
df['price'] = (df['price'] * 0.92).round(2)
alfa = df

In [5]:
alfa['product_name'] = alfa['product_name'].str.replace('-', ' ').str.replace(':', '').str.title()
alfa

                                 product_name  price
0            Adeptus Custodes Custodian Guard  56.12
1        Astra Telepathica Sisters Of Silence  46.00
2             Captain General Trajann Valoris  35.88
3          Adeptus Custodes Custodian Wardens  56.12
4            Adeptus Custodes Vertus Praetors  56.12
...                                       ...    ...
1615  Space Marine Heroes 3 F/Dispenser (Row)  11.96
1616       White Dwarf 460 (Jan 21) (English)   9.20
1617       White Dwarf 461 (Feb 21) (English)   9.20
1618       White Dwarf 458 (Nov 20) (English)   9.20
1619       White Dwarf 459 (Dec 20) (English)   9.20

[1620 rows x 2 columns]

In [6]:
words = alfa['product_name'].str.split()
alfa['faction'] = words.apply(lambda x: ' '.join(x[:-2]) if len(x) > 2 else np.nan)
alfa['mini'] = words.apply(lambda x: ' '.join(x[-2:]) if len(x) >= 2 else ' '.join(x))

beta = alfa.drop('product_name', axis=1)

In [7]:
# beta['faction'] = beta['faction'].str.replace(' ', '_')
beta.head(50)

     price                          faction                  mini
0    56.12                 Adeptus Custodes       Custodian Guard
1    46.00        Astra Telepathica Sisters            Of Silence
2    35.88                  Captain General       Trajann Valoris
3    56.12                 Adeptus Custodes     Custodian Wardens
4    56.12                 Adeptus Custodes       Vertus Praetors
5    46.92                 Adeptus Custodes    Allarus Custodians
6    33.12      Codex Adeptus Custodes (Hb)            (Abr.) Spa
7    37.72           Codex Adeptus Custodes        (Hb) (English)
8    17.48                Datacards Adeptus        Custodes (Eng)
9    37.72             Wh40K Kill Team Core      Manual (English)
10   37.72             Wh40K Kill Team Core      Manual (Spanish)
11  149.04             Warhammer 40000 Kill        Team (Spanish)
12  149.04             Warhammer 40000 Kill        Team (English)
13   56.12                        Kill Team  Commanders (Spanish)
14   56.12                        Kill Team  Commanders (English)
15   37.72                        Kill Team      Elites (Spanish)
16   37.72                        Kill Team      Elites (English)
17   92.92                         Killzone         Munitorum Hub
18   92.92                         Killzone     Sector Mechanicus
19   92.92                         Killzone      Sector Fronteris
20  149.04                 Kill Team Pariah       Nexus (Spanish)
21  149.04                 Kill Team Pariah       Nexus (English)
22   37.72                        Kill Team   Killzones (English)
23   37.72                        Kill Team   Killzones (Spanish)
24   10.12              Easy To Build Astra     Militarum Cadians
25   10.12          Etb Chaos Space Marines        Chaos Cultists
26   28.52                 Codex Deathwatch        (Hb) (English)
27   28.52                 Codex Deathwatch        (Hb) (Spanish)
28   14.72                        Datacards  Deathwatch (English)
29   35.88                              NaN   Deathwatch Veterans
30   74.52                       Deathwatch      Corvus Blackstar
31   32.20                       Deathwatch          Watch Master
32   13.80                              NaN   Deathwatch Upgrades
33  129.72                           Combat     Patrol Deathwatch
34   60.72             Warhammer 40000 Core        Book (English)
35   60.72             Warhammer 40000 Core        Book (Spanish)
36   92.00            Warhammer 40000 Elite     Edition (English)
37   92.00            Warhammer 40000 Elite     Edition (Spanish)
38   46.92                  Warhammer 40000     Recruit (Spanish)
39   46.92                  Warhammer 40000     Recruit (English)
40  153.64          Warhammer 40000 Command         Edition (Eng)
41  153.64          Warhammer 40000 Command         Edition (Spa)
42   14.72   Getting Started With Warhammer             40K (Eng)
43   14.72   Getting Started With Warhammer             40K (Spa)
44   37.72           Wh40K Chapter Approved        2020 (Spanish)
45   37.72           Wh40K Chapter Approved        2020 (English)
46   37.72   40Ktactical Deployment Mission              Pk (Eng)
47   37.72   40Ktactical Deployment Mission              Pk (Spa)
48   37.72  Beyond The Veil Crusade Mission              Pack Eng
49   37.72  Beyond The Veil Crusade Mission              Pack Spa

In [8]:
gamma = beta[~beta['faction'].str.contains('Kill|Warhammer|Codex|cards|Easy|Wh40|40|Citadel|Tape|Liquid|Contrast|Air|Shade|Dry|Technical|Layer|Journal|Battlezone|B/Z|Battlefield|Sector|S/Imperialis|Hh', na=False)]
gamma = gamma[~beta['mini'].str.contains('Cards|Spa|Eng|Pb|Hb|Celebration|Citadel|Book|(6 Pack)|Dice|Ruins|Novel', na=False)]
delta = gamma.reset_index(drop=True)

C:\Users\detla\AppData\Local\Temp\ipykernel_3128\251144370.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  gamma = gamma[~beta['mini'].str.contains('Cards|Spa|Eng|Pb|Hb|Celebration|Citadel|Book|(6 Pack)|Dice|Ruins|Novel', na=False)]
C:\Users\detla\AppData\Local\Temp\ipykernel_3128\251144370.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  gamma = gamma[~beta['mini'].str.contains('Cards|Spa|Eng|Pb|Hb|Celebration|Citadel|Book|(6 Pack)|Dice|Ruins|Novel', na=False)]

In [9]:
delta = delta.drop(index=delta.index[381:654]).reset_index(drop=True)
delta

     price                       faction               mini
0    56.12              Adeptus Custodes    Custodian Guard
1    46.00     Astra Telepathica Sisters         Of Silence
2    35.88               Captain General    Trajann Valoris
3    56.12              Adeptus Custodes  Custodian Wardens
4    56.12              Adeptus Custodes    Vertus Praetors
..     ...                           ...                ...
428  46.92             Daemons Of Khorne       Flesh Hounds
429  34.04             Karanak The Hound       Of Vengeance
430  32.20           Daemons Of Slaanesh         The Masque
431  23.92  B/Stone Fortress Cultists Of          The Abyss
432  11.96         Space Marine Heroes 3  F/Dispenser (Row)

[433 rows x 3 columns]

In [10]:
delta['all'] = delta['faction'].fillna('') + ' ' + delta['mini'].fillna('')
delta['all'] = delta['all'].str.strip()
epsilon = delta.drop(['faction', 'mini'], axis=1)
epsilon

     price                                      all
0    56.12         Adeptus Custodes Custodian Guard
1    46.00     Astra Telepathica Sisters Of Silence
2    35.88          Captain General Trajann Valoris
3    56.12       Adeptus Custodes Custodian Wardens
4    56.12         Adeptus Custodes Vertus Praetors
..     ...                                      ...
428  46.92           Daemons Of Khorne Flesh Hounds
429  34.04           Karanak The Hound Of Vengeance
430  32.20           Daemons Of Slaanesh The Masque
431  23.92   B/Stone Fortress Cultists Of The Abyss
432  11.96  Space Marine Heroes 3 F/Dispenser (Row)

[433 rows x 2 columns]

In [11]:
def assign_faction(text):
    if pd.isna(text):
        return np.nan
    
    factions = ['Craftworlds',
        'Drukhari',
        'Harlequins',
        'Ynnari',
        'Genestealer_Cult',
        'Tyranids',
        'Necrons',
        'Orks',
        'Tau_Empire',
        'Chaos_Space_Marines',
        'Space_Marines',
        'Supplement_Marines',
        'Blood_Angels',
        'Dark_Angels',
        'Space_Wolves',
        'Deathwatch',
        'Grey_Knights',
        'Astra_Militarum',
        'Adepta_Sororitas',
        'Adeptus_Custodes',
        'Adeptus_Mechanicus',
        'Imperial_Assassins',
        'Imperial_Knights',
        'Inquisition',
        'Chaos_Daemons',
        'Chaos_Knights',
        'Death_Guard',
        'Thousand_Sons']
    
    for f in factions:
        faction_name = f.replace('_', ' ')
        if faction_name in text:
            clean = text.replace(faction_name, '').strip()
            clean = ' '.join(clean.split())
            return f, clean
    return np.nan, text

epsilon[['faction', 'all']] = epsilon['all'].apply(assign_faction).apply(pd.Series)
epsilon

     price                                      all           faction
0    56.12                          Custodian Guard  Adeptus_Custodes
1    46.00     Astra Telepathica Sisters Of Silence               NaN
2    35.88          Captain General Trajann Valoris               NaN
3    56.12                        Custodian Wardens  Adeptus_Custodes
4    56.12                          Vertus Praetors  Adeptus_Custodes
..     ...                                      ...               ...
428  46.92           Daemons Of Khorne Flesh Hounds               NaN
429  34.04           Karanak The Hound Of Vengeance               NaN
430  32.20           Daemons Of Slaanesh The Masque               NaN
431  23.92   B/Stone Fortress Cultists Of The Abyss               NaN
432  11.96  Space Marine Heroes 3 F/Dispenser (Row)               NaN

[433 rows x 3 columns]

In [12]:
faction_map = {
    'Astra Telepathica': 'Adeptus_Custodes',
    'Chaos Space Marine': 'Chaos_Space_Marines',
    'Tallyman': 'Chaos_Daemons',
    'Black Legion': 'Chaos_Space_Marines',
    'Ultramarines': 'Supplement_Marines',
    'Iron Hand': 'Supplement_Marines',
    'Raven Guard': 'Supplement_Marines',
    'Salamanders': 'Supplement_Marines',
    'Imperial Fist': 'Supplement_Marines',
    'White Scar': 'Supplement_Marines',
    'Space Marine': 'Space_Marines',
    'S/Marine': 'Space_Marines',
    'Steel Legion': 'Astra_Militarum',
    'A/I': 'Astra_Militarum',
    'Dark Eldar': 'Drukhari',
    'Eldar Dark': 'Drukhari',
    "T'au": 'Tau_Empire',
    'Gunship': 'Tau_Empire',
    'Tau': 'Tau_Empire',
    'Harlequin': 'Harlequins',
    'Cult': 'Chaos_Daemons',
    'Ork': 'Orks',
    'Genestealers': 'Genestealer_Cult',
    'Tyranid': 'Tyranids',
    'Assassinorum': 'Imperial_Assassins',
    'A/Soror': 'Adepta_Sororitas'
}

name_map = {
    'Daemon': 'Chaos_Daemons',
    'Khorne': 'Chaos_Daemons',
    'Plague': 'Chaos_Daemons',
    'Tzeentch': 'Chaos_Daemons',
    'Kharn': 'Chaos_Daemons',
    'Cultist': 'Chaos_Daemons',
    'Skarbrand': 'Chaos_Daemons',
    'Syll': 'Chaos_Daemons',
    'Feculent': 'Chaos_Daemons',
    'Karanak': 'Chaos_Daemons',
    'Eisenhorn': 'Inquisition',
    'Ravenor': 'Inquisition',
    'Lord Inquisitor': 'Inquisition',
    'Lord Commissar': 'Inquisition',
    'Ciaphas Cain': 'Inquisition',
    'Marneus': 'Supplement_Marines',
    'Primaris': 'Space_Marines',
    'Militarum': 'Astra_Militarum',
    'Cadian': 'Astra_Militarum',
    'Aeronautica': 'Astra_Militarum',
    'Aer': 'Astra_Militarum',
    'Captain General': 'Adeptus_Custodes',
    'Daemons': 'Chaos_Daemons',
    'Chaos': 'Chaos_Daemons',
    'Saint': 'Adepta_Sororitas',
    'Knight': 'Imperial_Knights',
    'Titan': 'Imperial_Knights',
    'Mech': 'Adeptus_Mechanicus',
    'Talons': 'Adeptus_Custodes',
    'Tufts': 'Space_Marines',
    'Space Hulk': 'Space_Marines',
    'Kabalite': 'Drukhari',
    'Commissar': 'Astra_Militarum'
}

import re

def map_faction(text):
    if pd.isna(text):
        return np.nan, text
    
    # faction_map → SÍ elimina la coincidencia de 'all'
    for key, value in faction_map.items():
        pattern = r'\b' + re.escape(key) + r'\b'
        if re.search(pattern, text, re.IGNORECASE):
            clean = re.sub(pattern, '', text, flags=re.IGNORECASE).strip()
            clean = re.sub(r'\s+', ' ', clean).strip()
            return value, clean
    
    # name_map → NO elimina, conserva el texto original
    for key, value in name_map.items():
        pattern = r'\b' + re.escape(key) + r'\b'
        if re.search(pattern, text, re.IGNORECASE):
            return value, text
    
    return np.nan, text

# Aplicar fila por fila solo donde faction es NaN
for idx in epsilon[epsilon['faction'].isna()].index:
    faction, all_text = map_faction(epsilon.loc[idx, 'all'])
    epsilon.loc[idx, 'faction'] = faction
    epsilon.loc[idx, 'all'] = all_text

In [13]:
epsilon

     price                                     all           faction
0    56.12                         Custodian Guard  Adeptus_Custodes
1    46.00                      Sisters Of Silence  Adeptus_Custodes
2    35.88         Captain General Trajann Valoris  Adeptus_Custodes
3    56.12                       Custodian Wardens  Adeptus_Custodes
4    56.12                         Vertus Praetors  Adeptus_Custodes
..     ...                                     ...               ...
428  46.92          Daemons Of Khorne Flesh Hounds     Chaos_Daemons
429  34.04          Karanak The Hound Of Vengeance     Chaos_Daemons
430  32.20          Daemons Of Slaanesh The Masque     Chaos_Daemons
431  23.92  B/Stone Fortress Cultists Of The Abyss               NaN
432  11.96              Heroes 3 F/Dispenser (Row)     Space_Marines

[433 rows x 3 columns]

In [14]:
epsilon = epsilon.dropna().reset_index(drop=True)
epsilon = epsilon.rename(columns={'all': 'mini'})
epsilon[epsilon['faction'].isna()]

Empty DataFrame
Columns: [price, mini, faction]
Index: []

In [ ]:
epsilon.to_csv('../data/clear_data/df_prices_v2.csv', index=False)
epsilon

     price                             mini           faction
0    56.12                  Custodian Guard  Adeptus_Custodes
1    46.00               Sisters Of Silence  Adeptus_Custodes
2    35.88  Captain General Trajann Valoris  Adeptus_Custodes
3    56.12                Custodian Wardens  Adeptus_Custodes
4    56.12                  Vertus Praetors  Adeptus_Custodes
..     ...                              ...               ...
380  28.52     Bloodmaster Herald Of Khorne     Chaos_Daemons
381  46.92   Daemons Of Khorne Flesh Hounds     Chaos_Daemons
382  34.04   Karanak The Hound Of Vengeance     Chaos_Daemons
383  32.20   Daemons Of Slaanesh The Masque     Chaos_Daemons
384  11.96       Heroes 3 F/Dispenser (Row)     Space_Marines

[385 rows x 3 columns]