In [70]:
import numpy as np
import pandas as pd

In [71]:
df = pd.read_csv('data/faction_own.csv')
df

               faction  Owned  Primary
0     Adeptus Astartes   1497      610
1   Chaos Space Marine   1135      443
2              Necrons    692      139
3      Astra Militarum    522       93
4                 Orks    497      139
5          Craftworlds    478      128
6     Adeptus Custodes    478      118
7    Adeptus Sororitas    448      139
8                  Tau    452       93
9             Drukhari    395       70
10  Adeptus Mechanicus    395      116
11                 GSC    371       70
12            Tyranids    383      116
13             Daemons    371       46
14    Imperial Knights    325       23
15          Harlequins    255       23
16       Chaos Knights    232       12

In [72]:
df['faction'] = df['faction'].str.replace(' ', '_')
df

               faction  Owned  Primary
0     Adeptus_Astartes   1497      610
1   Chaos_Space_Marine   1135      443
2              Necrons    692      139
3      Astra_Militarum    522       93
4                 Orks    497      139
5          Craftworlds    478      128
6     Adeptus_Custodes    478      118
7    Adeptus_Sororitas    448      139
8                  Tau    452       93
9             Drukhari    395       70
10  Adeptus_Mechanicus    395      116
11                 GSC    371       70
12            Tyranids    383      116
13             Daemons    371       46
14    Imperial_Knights    325       23
15          Harlequins    255       23
16       Chaos_Knights    232       12

In [73]:
df.loc[df['faction'] == 'GSC', 'faction'] = df.loc[df['faction'] == 'GSC', 'faction'].str.replace('GSC', 'Genestealer_Cult')
df.loc[df['faction'] == 'Tau', 'faction'] = df.loc[df['faction'] == 'Tau', 'faction'].str.replace('Tau', 'Tau_Empire')
df.loc[df['faction'] == 'Adeptus_Sororitas', 'faction'] = df.loc[df['faction'] == 'Adeptus_Sororitas', 'faction'].str.replace('Adeptus_Sororitas', 'Adepta_Sororitas')
df.loc[df['faction'] == 'Daemons', 'faction'] = df.loc[df['faction'] == 'Daemons', 'faction'].str.replace('Daemons', 'Chaos_Daemons')
alfa = df.sort_values('faction', ascending=True)

In [74]:
alfa

               faction  Owned  Primary
7     Adepta_Sororitas    448      139
0     Adeptus_Astartes   1497      610
6     Adeptus_Custodes    478      118
10  Adeptus_Mechanicus    395      116
3      Astra_Militarum    522       93
13       Chaos_Daemons    371       46
16       Chaos_Knights    232       12
1   Chaos_Space_Marine   1135      443
5          Craftworlds    478      128
9             Drukhari    395       70
11    Genestealer_Cult    371       70
15          Harlequins    255       23
14    Imperial_Knights    325       23
2              Necrons    692      139
4                 Orks    497      139
8           Tau_Empire    452       93
12            Tyranids    383      116

In [75]:
faction_list = ['Craftworlds',
 'Drukhari',
 'Harlequins',
 'Ynnari',
 'Genestealer_Cult',
 'Tyranids',
 'Necrons',
 'Orks',
 'Tau_Empire',
 'Space_Marines',
 'Supplement_Marines',
 'Blood_Angels',
 'Dark_Angels',
 'Space_Wolves',
 'Deathwatch',
 'Grey_Knights',
 'Astra_Militarum',
 'Adepta_Sororitas',
 'Adeptus_Custodes',
 'Adeptus_Mechanicus',
 'Imperial_Assassins',
 'Imperial_Knights',
 'Inquisition',
 'Chaos_Daemons',
 'Chaos_Knights',
 'Chaos_Space_Marines',
 'Death_Guard',
 'Leagues_of_Votann'
 'Thousand_Sons']

In [76]:
faction_list.sort()
faction_list

['Adepta_Sororitas',
 'Adeptus_Custodes',
 'Adeptus_Mechanicus',
 'Astra_Militarum',
 'Blood_Angels',
 'Chaos_Daemons',
 'Chaos_Knights',
 'Chaos_Space_Marines',
 'Craftworlds',
 'Dark_Angels',
 'Death_Guard',
 'Deathwatch',
 'Drukhari',
 'Genestealer_Cult',
 'Grey_Knights',
 'Harlequins',
 'Imperial_Assassins',
 'Imperial_Knights',
 'Inquisition',
 'Leagues_of_VotannThousand_Sons',
 'Necrons',
 'Orks',
 'Space_Marines',
 'Space_Wolves',
 'Supplement_Marines',
 'Tau_Empire',
 'Tyranids',
 'Ynnari']

In [77]:
win = pd.read_csv('data/Win_Rate.csv', encoding='latin1')
win

,faction,Games,VP,Opp VP,Win %,Wins,Losses,Draws,Real Win %
0,Adepta Sororitas,17155,"63,24","62,26","50,18ï¿½%",8608,8246,301,50
1,Adeptus Custodes,28735,"63,66","61,04","52,52ï¿½%",15092,13216,427,52
2,Adeptus Mechanicus,11233,"62,48","62,98","49,28ï¿½%",5536,5487,210,49
3,Aeldari,25017,"61,85","62,98","48,12ï¿½%",12038,12593,386,48
4,Astra Militarum,30370,"60,38","63,07","47,09ï¿½%",14300,15578,492,47
5,Black Templars,17914,"60,41","61,13","48,46ï¿½%",8682,8936,296,48
6,Blood Angels,28697,"62,32","63,2","49,37ï¿½%",14167,14084,446,49
7,Chaos Daemons,16858,"66,39","62,95","53,47ï¿½%",9014,7583,261,53
8,Chaos Knights,20403,"64,1","62,41","52,46ï¿½%",10703,9428,272,52
9,Chaos Space Marines,27335,"59,47","63,15","44,82ï¿½%",12252,14659,424,44
10,Dark Angels,30235,"61,81","62,26","48,23ï¿½%",14582,15136,517,48
11,Death Guard,38993,"64,15","63,14","50,82ï¿½%",19816,18569,608,50
12,Deathwatch,4908,"61,88","61,24","49,88ï¿½%",2448,2384,76,49
13,Drukhari,15298,"64,36","63,59","49,39ï¿½%",7555,7502,241,49
14,Emperor's Children,23394,"60,58","61,78","48,24ï¿½%",11286,11759,349,48
15,Genestealer Cults,8718,"65,23","63,77","51,96ï¿½%",4530,4041,147,52
16,Grey Knights,14838,"61,53","62,77","47,13ï¿½%",6993,7617,228,47
17,Imperial Agents,1559,"60,69","66,66","43,94ï¿½%",685,849,25,43
18,Imperial Knights,21160,"62,93","61,84","52,25ï¿½%",11057,9818,285,52
19,Leagues Of Votann,19861,"63,5","63,13","49,44ï¿½%",9820,9733,308,49
20,Necrons,42331,"62,54","63,44","51,27ï¿½%",21702,19903,726,51
21,Orks,23532,"59,87","61,47","46,68ï¿½%",10984,12200,348,46
22,Space Marines,57238,"59,93","61,79","46,72ï¿½%",26740,29595,903,46
23,Space Wolves,21651,"60,74","61,78","48,46ï¿½%",10493,10792,366,48
24,T'au,28872,"62,75","62,98","47,85ï¿½%",13814,14578,480,47
25,Thousand Sons,20895,"61,08","61,29","49,64ï¿½%",10372,10178,345,49
26,Tyranids,36649,"61,68","61,91","49,63ï¿½%",18190,17835,624,49
27,World Eaters,32877,"62,74","62,15","50,58ï¿½%",16628,15788,461,50

In [78]:
win['faction'] = win['faction'].str.replace(' ', '_')
win['Win %'] = win['Win %'].str.replace('ï¿½%', '')
win

,faction,Games,VP,Opp VP,Win %,Wins,Losses,Draws,Real Win %
0,Adepta_Sororitas,17155,"63,24","62,26","50,18",8608,8246,301,50
1,Adeptus_Custodes,28735,"63,66","61,04","52,52",15092,13216,427,52
2,Adeptus_Mechanicus,11233,"62,48","62,98","49,28",5536,5487,210,49
3,Aeldari,25017,"61,85","62,98","48,12",12038,12593,386,48
4,Astra_Militarum,30370,"60,38","63,07","47,09",14300,15578,492,47
5,Black_Templars,17914,"60,41","61,13","48,46",8682,8936,296,48
6,Blood_Angels,28697,"62,32","63,2","49,37",14167,14084,446,49
7,Chaos_Daemons,16858,"66,39","62,95","53,47",9014,7583,261,53
8,Chaos_Knights,20403,"64,1","62,41","52,46",10703,9428,272,52
9,Chaos_Space_Marines,27335,"59,47","63,15","44,82",12252,14659,424,44
10,Dark_Angels,30235,"61,81","62,26","48,23",14582,15136,517,48
11,Death_Guard,38993,"64,15","63,14","50,82",19816,18569,608,50
12,Deathwatch,4908,"61,88","61,24","49,88",2448,2384,76,49
13,Drukhari,15298,"64,36","63,59","49,39",7555,7502,241,49
14,Emperor's_Children,23394,"60,58","61,78","48,24",11286,11759,349,48
15,Genestealer_Cults,8718,"65,23","63,77","51,96",4530,4041,147,52
16,Grey_Knights,14838,"61,53","62,77","47,13",6993,7617,228,47
17,Imperial_Agents,1559,"60,69","66,66","43,94",685,849,25,43
18,Imperial_Knights,21160,"62,93","61,84","52,25",11057,9818,285,52
19,Leagues_Of_Votann,19861,"63,5","63,13","49,44",9820,9733,308,49
20,Necrons,42331,"62,54","63,44","51,27",21702,19903,726,51
21,Orks,23532,"59,87","61,47","46,68",10984,12200,348,46
22,Space_Marines,57238,"59,93","61,79","46,72",26740,29595,903,46
23,Space_Wolves,21651,"60,74","61,78","48,46",10493,10792,366,48
24,T'au,28872,"62,75","62,98","47,85",13814,14578,480,47
25,Thousand_Sons,20895,"61,08","61,29","49,64",10372,10178,345,49
26,Tyranids,36649,"61,68","61,91","49,63",18190,17835,624,49
27,World_Eaters,32877,"62,74","62,15","50,58",16628,15788,461,50

In [79]:
win.loc[win['faction'] == "T'au", 'faction'] = win.loc[win['faction'] == "T'au", 'faction'].str.replace("T'au", 'Tau_Empire')
win.loc[win['faction'] == "Aeldari", 'faction'] = win.loc[win['faction'] == "Aeldari", 'faction'].str.replace("Aeldari", 'Craftworlds')
win.loc[win['faction'] == 'Genestealer_Cults', 'faction'] = win.loc[win['faction'] == 'Genestealer_Cults', 'faction'].str.replace('Genestealer_Cults', 'Genestealer_Cult')
win.sort_values('faction', ascending=True)

,faction,Games,VP,Opp VP,Win %,Wins,Losses,Draws,Real Win %
0,Adepta_Sororitas,17155,"63,24","62,26","50,18",8608,8246,301,50
1,Adeptus_Custodes,28735,"63,66","61,04","52,52",15092,13216,427,52
2,Adeptus_Mechanicus,11233,"62,48","62,98","49,28",5536,5487,210,49
4,Astra_Militarum,30370,"60,38","63,07","47,09",14300,15578,492,47
5,Black_Templars,17914,"60,41","61,13","48,46",8682,8936,296,48
6,Blood_Angels,28697,"62,32","63,2","49,37",14167,14084,446,49
7,Chaos_Daemons,16858,"66,39","62,95","53,47",9014,7583,261,53
8,Chaos_Knights,20403,"64,1","62,41","52,46",10703,9428,272,52
9,Chaos_Space_Marines,27335,"59,47","63,15","44,82",12252,14659,424,44
3,Craftworlds,25017,"61,85","62,98","48,12",12038,12593,386,48
10,Dark_Angels,30235,"61,81","62,26","48,23",14582,15136,517,48
11,Death_Guard,38993,"64,15","63,14","50,82",19816,18569,608,50
12,Deathwatch,4908,"61,88","61,24","49,88",2448,2384,76,49
13,Drukhari,15298,"64,36","63,59","49,39",7555,7502,241,49
14,Emperor's_Children,23394,"60,58","61,78","48,24",11286,11759,349,48
15,Genestealer_Cult,8718,"65,23","63,77","51,96",4530,4041,147,52
16,Grey_Knights,14838,"61,53","62,77","47,13",6993,7617,228,47
17,Imperial_Agents,1559,"60,69","66,66","43,94",685,849,25,43
18,Imperial_Knights,21160,"62,93","61,84","52,25",11057,9818,285,52
19,Leagues_Of_Votann,19861,"63,5","63,13","49,44",9820,9733,308,49
20,Necrons,42331,"62,54","63,44","51,27",21702,19903,726,51
21,Orks,23532,"59,87","61,47","46,68",10984,12200,348,46
22,Space_Marines,57238,"59,93","61,79","46,72",26740,29595,903,46
23,Space_Wolves,21651,"60,74","61,78","48,46",10493,10792,366,48
24,Tau_Empire,28872,"62,75","62,98","47,85",13814,14578,480,47
25,Thousand_Sons,20895,"61,08","61,29","49,64",10372,10178,345,49
26,Tyranids,36649,"61,68","61,91","49,63",18190,17835,624,49
27,World_Eaters,32877,"62,74","62,15","50,58",16628,15788,461,50

In [82]:
alfa = win.merge(df[['faction', 'Owned', 'Primary']], on='faction', how='left')
alfa

,faction,Games,VP,Opp VP,Win %,Wins,Losses,Draws,Real Win %,Owned,Primary
0,Adepta_Sororitas,17155,"63,24","62,26","50,18",8608,8246,301,50,448.0,139.0
1,Adeptus_Custodes,28735,"63,66","61,04","52,52",15092,13216,427,52,478.0,118.0
2,Adeptus_Mechanicus,11233,"62,48","62,98","49,28",5536,5487,210,49,395.0,116.0
3,Craftworlds,25017,"61,85","62,98","48,12",12038,12593,386,48,478.0,128.0
4,Astra_Militarum,30370,"60,38","63,07","47,09",14300,15578,492,47,522.0,93.0
5,Black_Templars,17914,"60,41","61,13","48,46",8682,8936,296,48,NaN,NaN
6,Blood_Angels,28697,"62,32","63,2","49,37",14167,14084,446,49,NaN,NaN
7,Chaos_Daemons,16858,"66,39","62,95","53,47",9014,7583,261,53,371.0,46.0
8,Chaos_Knights,20403,"64,1","62,41","52,46",10703,9428,272,52,232.0,12.0
9,Chaos_Space_Marines,27335,"59,47","63,15","44,82",12252,14659,424,44,NaN,NaN
10,Dark_Angels,30235,"61,81","62,26","48,23",14582,15136,517,48,NaN,NaN
11,Death_Guard,38993,"64,15","63,14","50,82",19816,18569,608,50,NaN,NaN
12,Deathwatch,4908,"61,88","61,24","49,88",2448,2384,76,49,NaN,NaN
13,Drukhari,15298,"64,36","63,59","49,39",7555,7502,241,49,395.0,70.0
14,Emperor's_Children,23394,"60,58","61,78","48,24",11286,11759,349,48,NaN,NaN
15,Genestealer_Cult,8718,"65,23","63,77","51,96",4530,4041,147,52,371.0,70.0
16,Grey_Knights,14838,"61,53","62,77","47,13",6993,7617,228,47,NaN,NaN
17,Imperial_Agents,1559,"60,69","66,66","43,94",685,849,25,43,NaN,NaN
18,Imperial_Knights,21160,"62,93","61,84","52,25",11057,9818,285,52,325.0,23.0
19,Leagues_Of_Votann,19861,"63,5","63,13","49,44",9820,9733,308,49,NaN,NaN
20,Necrons,42331,"62,54","63,44","51,27",21702,19903,726,51,692.0,139.0
21,Orks,23532,"59,87","61,47","46,68",10984,12200,348,46,497.0,139.0
22,Space_Marines,57238,"59,93","61,79","46,72",26740,29595,903,46,NaN,NaN
23,Space_Wolves,21651,"60,74","61,78","48,46",10493,10792,366,48,NaN,NaN
24,Tau_Empire,28872,"62,75","62,98","47,85",13814,14578,480,47,452.0,93.0
25,Thousand_Sons,20895,"61,08","61,29","49,64",10372,10178,345,49,NaN,NaN
26,Tyranids,36649,"61,68","61,91","49,63",18190,17835,624,49,383.0,116.0
27,World_Eaters,32877,"62,74","62,15","50,58",16628,15788,461,50,NaN,NaN

In [84]:
alfa.to_csv('clear_data/faction_own.csv', index=False)
alfa

,faction,Games,VP,Opp VP,Win %,Wins,Losses,Draws,Real Win %,Owned,Primary
0,Adepta_Sororitas,17155,"63,24","62,26","50,18",8608,8246,301,50,448.0,139.0
1,Adeptus_Custodes,28735,"63,66","61,04","52,52",15092,13216,427,52,478.0,118.0
2,Adeptus_Mechanicus,11233,"62,48","62,98","49,28",5536,5487,210,49,395.0,116.0
3,Craftworlds,25017,"61,85","62,98","48,12",12038,12593,386,48,478.0,128.0
4,Astra_Militarum,30370,"60,38","63,07","47,09",14300,15578,492,47,522.0,93.0
5,Black_Templars,17914,"60,41","61,13","48,46",8682,8936,296,48,NaN,NaN
6,Blood_Angels,28697,"62,32","63,2","49,37",14167,14084,446,49,NaN,NaN
7,Chaos_Daemons,16858,"66,39","62,95","53,47",9014,7583,261,53,371.0,46.0
8,Chaos_Knights,20403,"64,1","62,41","52,46",10703,9428,272,52,232.0,12.0
9,Chaos_Space_Marines,27335,"59,47","63,15","44,82",12252,14659,424,44,NaN,NaN
10,Dark_Angels,30235,"61,81","62,26","48,23",14582,15136,517,48,NaN,NaN
11,Death_Guard,38993,"64,15","63,14","50,82",19816,18569,608,50,NaN,NaN
12,Deathwatch,4908,"61,88","61,24","49,88",2448,2384,76,49,NaN,NaN
13,Drukhari,15298,"64,36","63,59","49,39",7555,7502,241,49,395.0,70.0
14,Emperor's_Children,23394,"60,58","61,78","48,24",11286,11759,349,48,NaN,NaN
15,Genestealer_Cult,8718,"65,23","63,77","51,96",4530,4041,147,52,371.0,70.0
16,Grey_Knights,14838,"61,53","62,77","47,13",6993,7617,228,47,NaN,NaN
17,Imperial_Agents,1559,"60,69","66,66","43,94",685,849,25,43,NaN,NaN
18,Imperial_Knights,21160,"62,93","61,84","52,25",11057,9818,285,52,325.0,23.0
19,Leagues_Of_Votann,19861,"63,5","63,13","49,44",9820,9733,308,49,NaN,NaN
20,Necrons,42331,"62,54","63,44","51,27",21702,19903,726,51,692.0,139.0
21,Orks,23532,"59,87","61,47","46,68",10984,12200,348,46,497.0,139.0
22,Space_Marines,57238,"59,93","61,79","46,72",26740,29595,903,46,NaN,NaN
23,Space_Wolves,21651,"60,74","61,78","48,46",10493,10792,366,48,NaN,NaN
24,Tau_Empire,28872,"62,75","62,98","47,85",13814,14578,480,47,452.0,93.0
25,Thousand_Sons,20895,"61,08","61,29","49,64",10372,10178,345,49,NaN,NaN
26,Tyranids,36649,"61,68","61,91","49,63",18190,17835,624,49,383.0,116.0
27,World_Eaters,32877,"62,74","62,15","50,58",16628,15788,461,50,NaN,NaN