In [12]:
import numpy as np
import pandas as pd

In [13]:
df = pd.read_csv('data/DS_Models.csv', sep='|')
df

,datasheet_id,line,name,M,T,Sv,inv_sv,inv_sv_descr,W,Ld,OC,base_size,base_size_descr,Unnamed: 13
0,1,1,Warboss,"6""",5,4+,5,NaN,6,6+,1,40mm,NaN,NaN
1,2,1,Warboss In Mega Armour,"5""",6,2+,5,NaN,7,6+,1,50mm,NaN,NaN
2,3,1,Warboss On Warbike,"12""",6,4+,5,NaN,7,6+,2,100 x 40mm,NaN,NaN
3,4,1,Weirdboy,"6""",5,5+,-,NaN,4,7+,1,40mm,NaN,NaN
4,6,1,Big Mek In Mega Armour,"5""",6,2+,-,NaN,5,7+,1,40mm,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1799,4209,1,Defiler,"12""",11,3+,5,NaN,18,6+,5,160mm,NaN,NaN
1800,4210,1,Thulia Ghuld,"8""",8,2+,4,NaN,10,6+,3,80mm,NaN,NaN
1801,4211,1,Hastarii Exterminators,"5""",4,3+,5,NaN,2,7+,1,32mm,NaN,NaN
1802,4212,1,Hastarii Fusiliers,"5""",4,3+,5,NaN,2,7+,1,32mm,NaN,NaN
1803,4213,1,Knight Destrier,"12""",10,3+,5,* against ranged attacks only,18,6+,8,150 x 95mm,NaN,NaN

In [14]:
cost = pd.read_csv('data/DS_Model_Costs.csv')
cost

      datasheet_id  line description  cost
0                1     1     1 model    75
1                2     1     1 model    80
2                3     1     1 model    75
3                4     1     1 model    65
4                6     1     1 model    90
...            ...   ...         ...   ...
2033          4146     1     1 model    70
2034          4146     2    2 models   140
2035          4147     1     1 model    75
2036          4148     1     1 model    85
2037          4149     1     1 model   425

[2038 rows x 4 columns]

In [15]:
df = df.merge(cost[['datasheet_id', 'cost']], on='datasheet_id', how='left')
df

,datasheet_id,line,name,M,T,Sv,inv_sv,inv_sv_descr,W,Ld,OC,base_size,base_size_descr,Unnamed: 13,cost
0,1,1,Warboss,"6""",5,4+,5,NaN,6,6+,1,40mm,NaN,NaN,75.0
1,2,1,Warboss In Mega Armour,"5""",6,2+,5,NaN,7,6+,1,50mm,NaN,NaN,80.0
2,3,1,Warboss On Warbike,"12""",6,4+,5,NaN,7,6+,2,100 x 40mm,NaN,NaN,75.0
3,4,1,Weirdboy,"6""",5,5+,-,NaN,4,7+,1,40mm,NaN,NaN,65.0
4,6,1,Big Mek In Mega Armour,"5""",6,2+,-,NaN,5,7+,1,40mm,NaN,NaN,90.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2231,4209,1,Defiler,"12""",11,3+,5,NaN,18,6+,5,160mm,NaN,NaN,NaN
2232,4210,1,Thulia Ghuld,"8""",8,2+,4,NaN,10,6+,3,80mm,NaN,NaN,NaN
2233,4211,1,Hastarii Exterminators,"5""",4,3+,5,NaN,2,7+,1,32mm,NaN,NaN,NaN
2234,4212,1,Hastarii Fusiliers,"5""",4,3+,5,NaN,2,7+,1,32mm,NaN,NaN,NaN
2235,4213,1,Knight Destrier,"12""",10,3+,5,* against ranged attacks only,18,6+,8,150 x 95mm,NaN,NaN,NaN

In [16]:
cols_to_drop = ['datasheet_id', 'line', 'M', 'T', 'Sv', 'inv_sv', 'inv_sv_descr', 'W', 'Ld', 'OC', 'base_size_descr', 'Unnamed: 13']

alfa = df.drop(columns=[c for c in cols_to_drop if c in df.columns])

alfa['name'].fillna('')
alfa = alfa.dropna(subset=['name'])

alfa = alfa.rename(columns={'name': 'mini'})
alfa

                        mini   base_size  cost
0                    Warboss        40mm  75.0
1     Warboss In Mega Armour        50mm  80.0
2         Warboss On Warbike  100 x 40mm  75.0
3                   Weirdboy        40mm  65.0
4     Big Mek In Mega Armour        40mm  90.0
...                      ...         ...   ...
2231                 Defiler       160mm   NaN
2232            Thulia Ghuld        80mm   NaN
2233  Hastarii Exterminators        32mm   NaN
2234      Hastarii Fusiliers        32mm   NaN
2235         Knight Destrier  150 x 95mm   NaN

[2213 rows x 3 columns]

In [17]:
alfa = alfa.rename(columns={'base_size': 'base_mm2'})

alfa['base_mm2'] = alfa['base_mm2'].replace(r'^\s*$', np.nan, regex=True)
alfa

                        mini    base_mm2  cost
0                    Warboss        40mm  75.0
1     Warboss In Mega Armour        50mm  80.0
2         Warboss On Warbike  100 x 40mm  75.0
3                   Weirdboy        40mm  65.0
4     Big Mek In Mega Armour        40mm  90.0
...                      ...         ...   ...
2231                 Defiler       160mm   NaN
2232            Thulia Ghuld        80mm   NaN
2233  Hastarii Exterminators        32mm   NaN
2234      Hastarii Fusiliers        32mm   NaN
2235         Knight Destrier  150 x 95mm   NaN

[2213 rows x 3 columns]

In [18]:
import re

def clean_mini(name):
    name = str(name)
    name = name.replace('"', "'").replace('"', "'").replace('`', "'").replace('´', "'").replace('’', "'")
    name = re.sub(r'\s+', ' ', name).strip()
    return name

alfa['mini'] = alfa['mini'].apply(clean_mini)

alfa

                        mini    base_mm2  cost
0                    Warboss        40mm  75.0
1     Warboss In Mega Armour        50mm  80.0
2         Warboss On Warbike  100 x 40mm  75.0
3                   Weirdboy        40mm  65.0
4     Big Mek In Mega Armour        40mm  90.0
...                      ...         ...   ...
2231                 Defiler       160mm   NaN
2232            Thulia Ghuld        80mm   NaN
2233  Hastarii Exterminators        32mm   NaN
2234      Hastarii Fusiliers        32mm   NaN
2235         Knight Destrier  150 x 95mm   NaN

[2213 rows x 3 columns]

In [19]:
alfa.to_csv('clear_data/df_models.csv', index=False)