In [144]:
import pandas as pd
import numpy as np

In [145]:
df = pd.read_csv('data/precios_of.csv')
df

,nounderline_URL,nounderline,Like1
0,https://www.warhammer.com/en-US/shop/legio-cus...,Custodian Dreadnought,$77.00
1,https://www.warhammer.com/en-US/shop/legio-cus...,Sentinel Guard Sodality,$73.50
2,https://www.warhammer.com/en-US/shop/legio-cus...,Shield Captain,$43.50
3,https://www.warhammer.com/en-US/shop/legio-cus...,Venatari Sodality,$82.00
4,https://www.warhammer.com/en-US/shop/legio-cus...,Custodian Guard Sodality,$73.50
...,...,...,...
931,https://www.warhammer.com/en-US/shop/kill-team...,Kill Team: Canoptek Circle,$77.00
932,https://www.warhammer.com/en-US/shop/ultramari...,Victrix Honour Guard,$65.00
933,https://www.warhammer.com/en-US/shop/marneus-c...,Marneus Calgar in Armour of Antilochus,$55.50
934,https://www.warhammer.com/en-US/shop/imperial-...,Knight Preceptor/Canis Rex,$194.00
935,https://www.warhammer.com/en-US/shop/seraptek-...,Seraptek Heavy Construct with Synaptic Obliter...,$400.00

In [146]:
alfa = df.iloc[0:, 1:]
alfa

                                           nounderline    Like1
0                                Custodian Dreadnought   $77.00
1                              Sentinel Guard Sodality   $73.50
2                                       Shield Captain   $43.50
3                                    Venatari Sodality   $82.00
4                             Custodian Guard Sodality   $73.50
..                                                 ...      ...
931                         Kill Team: Canoptek Circle   $77.00
932                               Victrix Honour Guard   $65.00
933             Marneus Calgar in Armour of Antilochus   $55.50
934                         Knight Preceptor/Canis Rex  $194.00
935  Seraptek Heavy Construct with Synaptic Obliter...  $400.00

[936 rows x 2 columns]

In [147]:
faction = ['Craftworlds',
 'Drukhari',
 'Harlequins',
 'Ynnari',
 'Genestealer_Cult',
 'Tyranids',
 'Necrons',
 'Orks',
 'Tau_Empire',
 'Space_Marines',
 'Supplement_Marines',
 'Blood_Angels',
 'Dark_Angels',
 'Space_Wolves',
 'Deathwatch',
 'Grey_Knights',
 'Astra_Militarum',
 'Adepta_Sororitas',
 'Adeptus_Custodes',
 'Adeptus_Mechanicus',
 'Imperial_Assassins',
 'Imperial_Knights',
 'Inquisition',
 'Chaos_Daemons',
 'Chaos_Knights',
 'Chaos_Space_Marines',
 'Death_Guard',
 'Thousand_Sons']

In [148]:
beta = alfa.rename(columns={'Like1': 'price'})
beta

                                           nounderline    price
0                                Custodian Dreadnought   $77.00
1                              Sentinel Guard Sodality   $73.50
2                                       Shield Captain   $43.50
3                                    Venatari Sodality   $82.00
4                             Custodian Guard Sodality   $73.50
..                                                 ...      ...
931                         Kill Team: Canoptek Circle   $77.00
932                               Victrix Honour Guard   $65.00
933             Marneus Calgar in Armour of Antilochus   $55.50
934                         Knight Preceptor/Canis Rex  $194.00
935  Seraptek Heavy Construct with Synaptic Obliter...  $400.00

[936 rows x 2 columns]

In [164]:
beta['price'] = beta['price'].str.replace('$', '')
beta

,nounderline,price,game,mini
0,Custodian Dreadnought,77.00,None,Custodian Dreadnought
1,Sentinel Guard Sodality,73.50,None,Sentinel Guard Sodality
2,Shield Captain,43.50,None,Shield Captain
3,Venatari Sodality,82.00,None,Venatari Sodality
4,Custodian Guard Sodality,73.50,None,Custodian Guard Sodality
...,...,...,...,...
931,Kill Team: Canoptek Circle,77.00,Kill Team,Canoptek Circle
932,Victrix Honour Guard,65.00,None,Victrix Honour Guard
933,Marneus Calgar in Armour of Antilochus,55.50,None,Marneus Calgar in Armour of Antilochus
934,Knight Preceptor/Canis Rex,194.00,None,Knight Preceptor/Canis Rex
935,Seraptek Heavy Construct with Synaptic Obliter...,400.00,None,Seraptek Heavy Construct with Synaptic Obliter...

In [166]:
beta['price'] = pd.to_numeric(beta['price'], errors='coerce')
beta['price'] = (beta['price'] * 0.92).round(2)
beta

,nounderline,price,game,mini
0,Custodian Dreadnought,70.84,None,Custodian Dreadnought
1,Sentinel Guard Sodality,67.62,None,Sentinel Guard Sodality
2,Shield Captain,40.02,None,Shield Captain
3,Venatari Sodality,75.44,None,Venatari Sodality
4,Custodian Guard Sodality,67.62,None,Custodian Guard Sodality
...,...,...,...,...
931,Kill Team: Canoptek Circle,70.84,Kill Team,Canoptek Circle
932,Victrix Honour Guard,59.80,None,Victrix Honour Guard
933,Marneus Calgar in Armour of Antilochus,51.06,None,Marneus Calgar in Armour of Antilochus
934,Knight Preceptor/Canis Rex,178.48,None,Knight Preceptor/Canis Rex
935,Seraptek Heavy Construct with Synaptic Obliter...,368.00,None,Seraptek Heavy Construct with Synaptic Obliter...

In [150]:
beta['game'] = beta['nounderline'].str.split(':').str[0]
beta['mini'] = beta['nounderline'].str.split(':').str[1]

no_colon = beta['mini'].isna()
beta.loc[no_colon, 'mini'] = beta.loc[no_colon, 'game']
beta.loc[no_colon, 'game'] = None

gamma = beta.drop('nounderline', axis=1)
gamma

      price       game                                               mini
0     77.00       None                              Custodian Dreadnought
1     73.50       None                            Sentinel Guard Sodality
2     43.50       None                                     Shield Captain
3     82.00       None                                  Venatari Sodality
4     73.50       None                           Custodian Guard Sodality
..      ...        ...                                                ...
931   77.00  Kill Team                                    Canoptek Circle
932   65.00       None                               Victrix Honour Guard
933   55.50       None             Marneus Calgar in Armour of Antilochus
934  194.00       None                         Knight Preceptor/Canis Rex
935  400.00       None  Seraptek Heavy Construct with Synaptic Obliter...

[936 rows x 3 columns]

In [151]:
gamma['faction'] = gamma['game'].apply(
    lambda x: x if str(x).lower() in faction else None
)
gamma

,price,game,mini,faction
0,77.00,None,Custodian Dreadnought,None
1,73.50,None,Sentinel Guard Sodality,None
2,43.50,None,Shield Captain,None
3,82.00,None,Venatari Sodality,None
4,73.50,None,Custodian Guard Sodality,None
...,...,...,...,...
931,77.00,Kill Team,Canoptek Circle,None
932,65.00,None,Victrix Honour Guard,None
933,55.50,None,Marneus Calgar in Armour of Antilochus,None
934,194.00,None,Knight Preceptor/Canis Rex,None
935,400.00,None,Seraptek Heavy Construct with Synaptic Obliter...,None

In [152]:
mat = pd.read_csv('clear_data/df_materials.csv')
mat

,mini,faction,material,edition,year
0,Baharroth Wings,Craftworlds,Metal,Warhammer 40K: Rogue Trader,1990.0
1,Warp Spiders,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0
2,Avatar of Khaine,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0
3,Asurmen,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0
4,Karandras,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0
...,...,...,...,...,...
977,Ahriman,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2016.0
978,Tzaangor Enlightened,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017.0
979,Tzaangor Skyfires,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017.0
980,Tzaangor Shaman,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017.0
981,Infernal Master,Thousand_Sons,Plastic,Warhammer 40K: 9th Edition,2021.0

In [ ]:
# Left join: mantiene todas las filas de mat, agrega precio de gamma
delta = mat.merge(gamma[['mini', 'price']], on='mini', how='left')
delta

,mini,faction,material,edition,year,price
0,Baharroth Wings,Craftworlds,Metal,Warhammer 40K: Rogue Trader,1990.0,NaN
1,Warp Spiders,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0,62.50
2,Avatar of Khaine,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0,114.00
3,Asurmen,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0,48.00
4,Karandras,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0,NaN
...,...,...,...,...,...,...
979,Ahriman,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2016.0,48.00
980,Tzaangor Enlightened,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017.0,60.00
981,Tzaangor Skyfires,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017.0,NaN
982,Tzaangor Shaman,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017.0,39.00
983,Infernal Master,Thousand_Sons,Plastic,Warhammer 40K: 9th Edition,2021.0,43.50

In [159]:
delta['price'].isna().sum()

np.int64(486)

In [ ]:
# faction_map = {
#     'Craftworld': 'Craftworlds',
#     'Aeldari': 'Craftworlds',
#     'Farseer': 'Craftworlds',
#     'Howling Banshee': 'Craftworlds',
#     'Dire Avenger': 'Craftworlds',
#     'Warp Spider': 'Craftworlds',
#     'Swooping Hawk': 'Craftworlds',
#     'Striking Scorpion': 'Craftworlds',
#     'Fire Dragon': 'Craftworlds',
#     'Guardian': 'Craftworlds',
#     'Warlock': 'Craftworlds',
#     'Avatar': 'Craftworlds',
#     'Vyper': 'Craftworlds',
#     'Wave Serpent': 'Craftworlds',
#     'Wraithguard': 'Craftworlds',
#     'Wraithlord': 'Craftworlds',
#     'Wraithknight': 'Craftworlds',
#     'Ranger': 'Craftworlds',
#     'Warlock': 'Craftworlds',
#     'Shining Spear': 'Craftworlds',
    
#     'Drukhari': 'Drukhari',
#     'Dark Eldar': 'Drukhari',
#     'Kabalite': 'Drukhari',
#     'Wych': 'Drukhari',
#     'Incubi': 'Drukhari',
#     'Haemonculus': 'Drukhari',
#     'Archon': 'Drukhari',
#     'Succubus': 'Drukhari',
#     'Reaver': 'Drukhari',
#     'Hellion': 'Drukhari',
#     'Mandrake': 'Drukhari',
#     'Ravager': 'Drukhari',
#     'Raider': 'Drukhari',
#     'Venom': 'Drukhari',
#     'Cronos': 'Drukhari',
#     'Talos': 'Drukhari',
#     'Lelith': 'Drukhari',
#     'Drazhar': 'Drukhari',
#     'Grotesque': 'Drukhari',
#     'Wrack': 'Drukhari',
#     'Scourge': 'Drukhari',
    
#     'Harlequin': 'Harlequins',
#     'Troupe': 'Harlequins',
#     'Shadowseer': 'Harlequins',
#     'Death Jester': 'Harlequins',
#     'Solitaire': 'Harlequins',
#     'Voidweaver': 'Harlequins',
#     'Starweaver': 'Harlequins',
    
#     'Ynnari': 'Ynnari',
#     'Yvraine': 'Ynnari',
#     'The Visarch': 'Ynnari',
#     'The Yncarne': 'Ynnari',
    
#     'Genestealer': 'Genestealer_Cult',
#     'GSC': 'Genestealer_Cult',
#     'Cultist': 'Genestealer_Cult',
#     'Acolyte': 'Genestealer_Cult',
#     'Patriarch': 'Genestealer_Cult',
#     'Magus': 'Genestealer_Cult',
#     'Metamorph': 'Genestealer_Cult',
#     'Neophyte': 'Genestealer_Cult',
#     'Aberrant': 'Genestealer_Cult',
#     'Kelermorph': 'Genestealer_Cult',
    
#     'Tyranid': 'Tyranids',
#     'Hive Guard': 'Tyranids',
#     'Hormagaunt': 'Tyranids',
#     'Termagant': 'Tyranids',
#     'Gaunt': 'Tyranids',
#     'Warrior': 'Tyranids',
#     'Carnifex': 'Tyranids',
#     'Trygon': 'Tyranids',
#     'Ravener': 'Tyranids',
#     'Lictor': 'Tyranids',
#     'Haruspex': 'Tyranids',
#     'Zoanthrope': 'Tyranids',
#     'Neurotyrant': 'Tyranids',
#     'Biovores': 'Tyranids',
#     'Myphitic': 'Tyranids',
#     'Tervigon': 'Tyranids',
#     'Old One Eye': 'Tyranids',
#     'The Swarmlord': 'Tyranids',
#     'Hive Tyrant': 'Tyranids',
#     'Neurothrope': 'Tyranids',
    
#     'Necron': 'Necrons',
#     'Immortal': 'Necrons',
#     'Warrior': 'Necrons',
#     'Lychguard': 'Necrons',
#     'Deathmark': 'Necrons',
#     'Flayed One': 'Necrons',
#     'Canoptek': 'Necrons',
#     'Monolith': 'Necrons',
#     'Ghost Ark': 'Necrons',
#     'Night Scythe': 'Necrons',
#     'Doom Scythe': 'Necrons',
#     'Tomb Blade': 'Necrons',
#     'Spyder': 'Necrons',
#     'Overlord': 'Necrons',
#     'Cryptek': 'Necrons',
#     'Lord': 'Necrons',
#     'Triarch': 'Necrons',
#     'Wraith': 'Necrons',
#     'Destroyer': 'Necrons',
#     'Cairn': 'Necrons',
    
#     'Ork': 'Orks',
#     'Boyz': 'Orks',
#     'Nob': 'Orks',
#     'Warboss': 'Orks',
#     'Mek': 'Orks',
#     'Weirdboy': 'Orks',
#     'Dok': 'Orks',
#     'Flash Gitz': 'Orks',
#     'Burna': 'Orks',
#     'Shoota': 'Orks',
#     'Slugga': 'Orks',
#     'Trukk': 'Orks',
#     'Deff Dread': 'Orks',
#     'Killa Kan': 'Orks',
#     'Looted Wagon': 'Orks',
#     'Big Mek': 'Orks',
#     'Ghazghkull': 'Orks',
#     'Gretchin': 'Orks',
#     'Snotling': 'Orks',
    
#     'Tau': 'Tau_Empire',
#     "T'au": 'Tau_Empire',
#     'Fire Warrior': 'Tau_Empire',
#     'Crisis': 'Tau_Empire',
#     'Broadside': 'Tau_Empire',
#     'Riptide': 'Tau_Empire',
#     'Pathfinder': 'Tau_Empire',
#     'Stealth': 'Tau_Empire',
#     'Piranha': 'Tau_Empire',
#     'Hammerhead': 'Tau_Empire',
#     'Skyray': 'Tau_Empire',
#     'XV': 'Tau_Empire',
#     'Commander': 'Tau_Empire',
#     'Ethereal': 'Tau_Empire',
#     'Devilfish': 'Tau_Empire',
    
#     'Space Marine': 'Space_Marines',
#     'Primaris': 'Space_Marines',
#     'Intercessor': 'Space_Marines',
#     'Tactical': 'Space_Marines',
#     'Devastator': 'Space_Marines',
#     'Assault': 'Space_Marines',
#     'Sternguard': 'Space_Marines',
#     'Vanguard': 'Space_Marines',
#     'Scout': 'Space_Marines',
#     'Aggressor': 'Space_Marines',
#     'Eliminator': 'Space_Marines',
#     'Inceptor': 'Space_Marines',
#     'Suppressor': 'Space_Marines',
#     'Reiver': 'Space_Marines',
#     'Hellblaster': 'Space_Marines',
#     'Outrider': 'Space_Marines',
#     'Whirlwind': 'Space_Marines',
#     'Rhino': 'Space_Marines',
#     'Predator': 'Space_Marines',
#     'Land Raider': 'Space_Marines',
#     'Republik': 'Space_Marines',
#     'Impulsor': 'Space_Marines',
#     'Gladiator': 'Space_Marines',
    
#     'Blood Angel': 'Blood_Angels',
#     'Sanguinius': 'Blood_Angels',
#     'Dante': 'Blood_Angels',
#     'Death Company': 'Blood_Angels',
#     'Furioso': 'Blood_Angels',
#     'Baal': 'Blood_Angels',
#     'Lemartes': 'Blood_Angels',
    
#     'Dark Angel': 'Dark_Angels',
#     'Inner Circle': 'Dark_Angels',
#     'Belial': 'Dark_Angels',
#     'Ravenwing': 'Dark_Angels',
#     'Deathwing': 'Dark_Angels',
    
#     'Space Wolf': 'Space_Wolves',
#     'Wolf': 'Space_Wolves',
#     'Thunderwolf': 'Space_Wolves',
#     'Rune Priest': 'Space_Wolves',
#     'Iron Priest': 'Space_Wolves',
#     'Wolf Lord': 'Space_Wolves',
#     'Wulfen': 'Space_Wolves',
#     'Blood Claw': 'Space_Wolves',
#     'Stormwolf': 'Space_Wolves',
    
#     'Deathwatch': 'Deathwatch',
#     'Kill Team': 'Deathwatch',
#     'Watch Master': 'Deathwatch',
#     'Veteran': 'Deathwatch',
    
#     'Grey Knight': 'Grey_Knights',
#     'Brother': 'Grey_Knights',
#     'Justicar': 'Grey_Knights',
#     'Castellan': 'Grey_Knights',
#     'Venerable': 'Grey_Knights',
#     'Nemesis': 'Grey_Knights',
#     'Purifier': 'Grey_Knights',
    
#     'Astra Militarum': 'Astra_Militarum',
#     'Guard': 'Astra_Militarum',
#     'Cadian': 'Astra_Militarum',
#     'Krieg': 'Astra_Militarum',
#     'Kasrkin': 'Astra_Militarum',
#     'Conscript': 'Astra_Militarum',
#     'Veteran': 'Astra_Militarum',
#     'Chimera': 'Astra_Militarum',
#     'Leman Russ': 'Astra_Militarum',
#     'Basilisk': 'Astra_Militarum',
#     'Baneblade': 'Astra_Militarum',
#     'Trooper': 'Astra_Militarum',
#     'Ogryn': 'Astra_Militarum',
#     'Ratling': 'Astra_Militarum',
#     'Commissar': 'Astra_Militarum',
#     'Lord Solar': 'Astra_Militarum',
#     'Tempestus': 'Astra_Militarum',
    
#     'Sororitas': 'Adepta_Sororitas',
#     'Sister': 'Adepta_Sororitas',
#     'Adepta': 'Adepta_Sororitas',
#     'Canoness': 'Adepta_Sororitas',
#     'Palatine': 'Adepta_Sororitas',
#     'Seraphim': 'Adepta_Sororitas',
#     'Celestian': 'Adepta_Sororitas',
#     'Dominion': 'Adepta_Sororitas',
#     'Battle Sister': 'Adepta_Sororitas',
#     'Novitiate': 'Adepta_Sororitas',
#     'Hospitaller': 'Adepta_Sororitas',
#     'Preacher': 'Adepta_Sororitas',
#     'Imagifier': 'Adepta_Sororitas',
#     'Celestine': 'Adepta_Sororitas',
#     'Paragon': 'Adepta_Sororitas',
#     'Exorcist': 'Adepta_Sororitas',
#     'Retributor': 'Adepta_Sororitas',
#     'Rhino': 'Adepta_Sororitas',
    
#     'Custodian': 'Adeptus_Custodes',
#     'Custodes': 'Adeptus_Custodes',
#     'Shield Captain': 'Adeptus_Custodes',
#     'Vertus Praetor': 'Adeptus_Custodes',
#     'Sagittarum': 'Adeptus_Custodes',
#     'Vexilus': 'Adeptus_Custodes',
#     'Valiant': 'Adeptus_Custodes',
#     'Telemon': 'Adeptus_Custodes',
#     'Contemptor': 'Adeptus_Custodes',
#     'Allarus': 'Adeptus_Custodes',
#     'Guardian': 'Adeptus_Custodes',
#     'Castellan': 'Adeptus_Custodes',
#     'Trajann': 'Adeptus_Custodes',
#     'Solaria': 'Adeptus_Custodes',
    
#     'Adeptus Mechanicus': 'Adeptus_Mechanicus',
#     'AdMech': 'Adeptus_Mechanicus',
#     'Skorpius': 'Adeptus_Mechanicus',
#     'Kastelan': 'Adeptus_Mechanicus',
#     'Sydonian': 'Adeptus_Mechanicus',
#     'Ironstrider': 'Adeptus_Mechanicus',
#     'Techpriest': 'Adeptus_Mechanicus',
#     'Enginseer': 'Adeptus_Mechanicus',
#     'Secutarii': 'Adeptus_Mechanicus',
#     'Peltast': 'Adeptus_Mechanicus',
#     'Hoplite': 'Adeptus_Mechanicus',
#     'Maniple': 'Adeptus_Mechanicus',
#     'Kataphron': 'Adeptus_Mechanicus',
#     'Onslaught': 'Adeptus_Mechanicus',
#     'Cawl': 'Adeptus_Mechanicus',
    
#     'Imperial Assassin': 'Imperial_Assassins',
#     'Assassin': 'Imperial_Assassins',
#     'Vindicare': 'Imperial_Assassins',
#     'Eversor': 'Imperial_Assassins',
#     'Callidus': 'Imperial_Assassins',
#     'Culexus': 'Imperial_Assassins',
    
#     'Imperial Knight': 'Imperial_Knights',
#     'Knight': 'Imperial_Knights',
#     'Paladin': 'Imperial_Knights',
#     'Errant': 'Imperial_Knights',
#     'Crusader': 'Imperial_Knights',
#     'Warden': 'Imperial_Knights',
#     'Gallant': 'Imperial_Knights',
#     'Armiger': 'Imperial_Knights',
#     'Moira': 'Imperial_Knights',
#     'Questoris': 'Imperial_Knights',
#     'Castellan': 'Imperial_Knights',
#     'Warmaster': 'Imperial_Knights',
    
#     'Inquisitor': 'Inquisition',
#     'Inquisition': 'Inquisition',
#     'Acolyte': 'Inquisition',
    
#     'Chaos Daemon': 'Chaos_Daemons',
#     'Daemon': 'Chaos_Daemons',
#     'Bloodthirster': 'Chaos_Daemons',
#     'Lord of Change': 'Chaos_Daemons',
#     'Great Unclean One': 'Chaos_Daemons',
#     'Keeper of Secrets': 'Chaos_Daemons',
#     'Bloodletter': 'Chaos_Daemons',
#     'Horror': 'Chaos_Daemons',
#     'Plaguebearer': 'Chaos_Daemons',
#     'Daemonette': 'Chaos_Daemons',
#     'Screamer': 'Chaos_Daemons',
#     'Exalted': 'Chaos_Daemons',
    
#     'Chaos Knight': 'Chaos_Knights',
#     'Desecrator': 'Chaos_Knights',
#     'Decimator': 'Chaos_Knights',
#     'Shroud': 'Chaos_Knights',
#     'Stalker': 'Chaos_Knights',
#     'Warg': 'Chaos_Knights',
#     'Abominant': 'Chaos_Knights',
#     'Mourneblade': 'Chaos_Knights',
    
#     'Chaos Space Marine': 'Chaos_Space_Marines',
#     'CSM': 'Chaos_Space_Marines',
#     'Chaos': 'Chaos_Space_Marines',
#     'Legion': 'Chaos_Space_Marines',
#     'Champion': 'Chaos_Space_Marines',
#     'Obliterator': 'Chaos_Space_Marines',
#     'Possessed': 'Chaos_Space_Marines',
#     'Havoc': 'Chaos_Space_Marines',
#     'Raptor': 'Chaos_Space_Marines',
#     'Sorcerer': 'Chaos_Space_Marines',
#     'Terminator': 'Chaos_Space_Marines',
#     'Cultist': 'Chaos_Space_Marines',
    
#     'Death Guard': 'Death_Guard',
#     'Plague': 'Death_Guard',
#     'Nurgle': 'Death_Guard',
#     'Mortarion': 'Death_Guard',
#     'Poxwalker': 'Death_Guard',
#     'Poxbrute': 'Death_Guard',
#     'Foetid Bloat': 'Death_Guard',
#     'Blasphemy': 'Death_Guard',
#     'Spawn': 'Death_Guard',
    
#     'Thousand Son': 'Thousand_Sons',
#     'Tzeentch': 'Thousand_Sons',
#     'Magnus': 'Thousand_Sons',
#     'Rubric': 'Thousand_Sons',
#     'Sorcerer': 'Thousand_Sons',
#     'Chaos Lord': 'Thousand_Sons',
#     'Mutalith': 'Thousand_Sons',
# }

# # Asignar faction usando el mapa
# gamma['faction'] = None
# for keyword, faction_name in faction_map.items():
#     mask = gamma['mini'].str.contains(keyword, case=False, na=False)
#     gamma.loc[mask, 'faction'] = faction_name
# gamma

,price,game,mini,faction
0,77.00,None,Custodian Dreadnought,Adeptus_Custodes
1,73.50,None,Sentinel Guard Sodality,Astra_Militarum
2,43.50,None,Shield Captain,Adeptus_Custodes
3,82.00,None,Venatari Sodality,None
4,73.50,None,Custodian Guard Sodality,Adeptus_Custodes
...,...,...,...,...
931,77.00,Kill Team,Canoptek Circle,Necrons
932,65.00,None,Victrix Honour Guard,Astra_Militarum
933,55.50,None,Marneus Calgar in Armour of Antilochus,None
934,194.00,None,Knight Preceptor/Canis Rex,Imperial_Knights
935,400.00,None,Seraptek Heavy Construct with Synaptic Obliter...,Chaos_Space_Marines