In [79]:
import pandas as pd
import numpy as np

In [80]:
df = pd.read_csv('data/prices.csv')
df

      ss_code                             product_name  price currency
0       01-07         ADEPTUS CUSTODES CUSTODIAN GUARD   61.0      USD
1       01-08     ASTRA TELEPATHICA SISTERS OF SILENCE   50.0      USD
2       01-10          CAPTAIN-GENERAL TRAJANN VALORIS   39.0      USD
3       01-11       ADEPTUS CUSTODES CUSTODIAN WARDENS   61.0      USD
4       01-12         ADEPTUS CUSTODES VERTUS PRAETORS   61.0      USD
...       ...                                      ...    ...      ...
1615   SMH-05  SPACE MARINE HEROES 3 F/DISPENSER (ROW)   13.0      USD
1616  WD01-60       WHITE DWARF 460 (JAN-21) (ENGLISH)   10.0      USD
1617  WD02-60       WHITE DWARF 461 (FEB-21) (ENGLISH)   10.0      USD
1618  WD11-60       WHITE DWARF 458 (NOV-20) (ENGLISH)   10.0      USD
1619  WD12-60       WHITE DWARF 459 (DEC-20) (ENGLISH)   10.0      USD

[1620 rows x 4 columns]

In [81]:
df = df.drop(columns=['ss_code', 'currency'])
df

                                 product_name  price
0            ADEPTUS CUSTODES CUSTODIAN GUARD   61.0
1        ASTRA TELEPATHICA SISTERS OF SILENCE   50.0
2             CAPTAIN-GENERAL TRAJANN VALORIS   39.0
3          ADEPTUS CUSTODES CUSTODIAN WARDENS   61.0
4            ADEPTUS CUSTODES VERTUS PRAETORS   61.0
...                                       ...    ...
1615  SPACE MARINE HEROES 3 F/DISPENSER (ROW)   13.0
1616       WHITE DWARF 460 (JAN-21) (ENGLISH)   10.0
1617       WHITE DWARF 461 (FEB-21) (ENGLISH)   10.0
1618       WHITE DWARF 458 (NOV-20) (ENGLISH)   10.0
1619       WHITE DWARF 459 (DEC-20) (ENGLISH)   10.0

[1620 rows x 2 columns]

In [88]:
df['price'] = (df['price'] * 0.92).round(2)
alfa = df

In [95]:
alfa['product_name'] = alfa['product_name'].str.title().replace('-', ' ')
alfa

                                 product_name  price
0            Adeptus Custodes Custodian Guard  51.63
1        Astra Telepathica Sisters Of Silence  42.32
2             Captain-General Trajann Valoris  33.01
3          Adeptus Custodes Custodian Wardens  51.63
4            Adeptus Custodes Vertus Praetors  51.63
...                                       ...    ...
1615  Space Marine Heroes 3 F/Dispenser (Row)  11.00
1616       White Dwarf 460 (Jan-21) (English)   8.46
1617       White Dwarf 461 (Feb-21) (English)   8.46
1618       White Dwarf 458 (Nov-20) (English)   8.46
1619       White Dwarf 459 (Dec-20) (English)   8.46

[1620 rows x 2 columns]

In [75]:
split_alfa = alfa['product_name'].str.split(n=2, expand=True)
alfa['faction'] = split_alfa[0] + ' ' + split_alfa[1]
alfa['mini'] = split_alfa[2]
beta = alfa.drop('product_name', axis=1)

In [76]:
beta

      price                  faction                        mini
0     56.12         Adeptus Custodes             Custodian Guard
1     46.00        Astra Telepathica          Sisters Of Silence
2     35.88  Captain-General Trajann                     Valoris
3     56.12         Adeptus Custodes           Custodian Wardens
4     56.12         Adeptus Custodes             Vertus Praetors
...     ...                      ...                         ...
1615  11.96             Space Marine  Heroes 3 F/Dispenser (Row)
1616   9.20              White Dwarf      460 (Jan-21) (English)
1617   9.20              White Dwarf      461 (Feb-21) (English)
1618   9.20              White Dwarf      458 (Nov-20) (English)
1619   9.20              White Dwarf      459 (Dec-20) (English)

[1620 rows x 3 columns]

In [77]:
mat = pd.read_csv('clear_data/df_materials.csv')
mat

,mini,faction,material,edition,year
0,Baharroth Wings,Craftworlds,Metal,Warhammer 40K: Rogue Trader,1990.0
1,Warp Spiders,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0
2,Avatar of Khaine,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0
3,Asurmen,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0
4,Karandras,Craftworlds,Finecast,Warhammer 40K: 2nd Edition,1994.0
...,...,...,...,...,...
977,Ahriman,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2016.0
978,Tzaangor Enlightened,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017.0
979,Tzaangor Skyfires,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017.0
980,Tzaangor Shaman,Thousand_Sons,Plastic,Warhammer 40K: 7th Edition,2017.0
981,Infernal Master,Thousand_Sons,Plastic,Warhammer 40K: 9th Edition,2021.0